### ISSUE TITLE
promise implementation does not seem to work

### ISSUE THREAD

**Issue by crucidal** [coinbase/gdax-node#102]
Despite the documented promise-approach I am getting the follow error:

> wip/node_modules/gdax/lib/clients/public.js:57
      throw "Must supply a callback."

**index.js**
```
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();

publicClient
  .getProducts()
  .then(data => {
      // work with data
  })
  .catch(error => {
     // handle the error
  });
```

**Comment by crucidal** [comment]
Nevermind... installation using github works... (so I guess the version in npm is not up-to-date)

**Comment by JakeRad** [comment]
His this issue too ... please update nom version.
