### ISSUE TITLE
"Size" parameter always required for Market orders

### ISSUE THREAD

**Issue by simlay** [coinbase/gdax-node#11]
According to https://docs.gdax.com/#place-a-new-order:

```
MARKET ORDER PARAMETERS

Param   Description
size    [optional]* Desired amount in BTC
funds   [optional]* Desired amount of quote currency to use

* One of size or funds is _required.
```

So, the following should work to place an order:

```
var buyParams = {
    'funds': 1, // USD,
    'currency': 'BTC',
    'type': 'market',
};
authedClient.buy(buyParams, callback);
```

Anyway, it looks like [size is always required](https://github.com/coinbase/gdax-node/blob/57afad7f7c401ccc6da36d273f14703f0c8a8ea0/lib/clients/authenticated.js#L121-L131) rather than just one of `size` or `funds`.

**Comment by poffdeluxe** [comment]
I put up a simple PR for this guy.
