### ISSUE TITLE
error "Must supply a callback" in promise, node 8, public data

### ISSUE THREAD

**Issue by nicolasxu** [coinbase/gdax-node#111]
```
publicClient
  .getProducts()
  .then(data => {
    // work with data
  })
  .catch(error => {
    // handle the error
  });
```

.../node_modules/gdax/lib/clients/public.js:57
      throw "Must supply a callback."
      ^
Must supply a callback.

**Comment by glintik** [comment]
Hi @nicolasxu, looks like a broken package in npm, just install it from github:
```
npm install coinbase/gdax-node
```
P.S. Not working for Coinbase.

**Comment by fb55** [comment]
Thanks @glintik — we need to publish an update of this library at some point

**Comment by goleary91** [comment]
any word on publishing an update?  I installed from github, but it would be good to get the latest on npm for new users who are onboarding

**Comment by sjc01234** [comment]
I used npm and only thru this issue discovered i needed to install from github

**Comment by nischayv** [comment]
+1 Faced the same problem

**Comment by ajhurliman** [comment]
Still a problem installing through NPM.

**Comment by rmm5t** [comment]
See #148
