### ISSUE TITLE
Gdax.OrderbookSync 0.4.2 is out of sync and dropping messages

### ISSUE THREAD

**Issue by joelnet** [coinbase/gdax-node#114]
I am placing orders using `Gdax.AuthenticatedClient`'s `buy` method. This works and returns an order object.

I am watching for these id's using the `Gdax.OrderbookSync`'s socket.

```
const orderbookSync = new Gdax.OrderbookSync()
orderbookSync.socket.on('message', message => {
  const order = JSON.parse(message)
  if (order.order_id === myOrder.id) {
    console.log(message)
  }
})
```

For most orders, I will see a `received`, `open`,  `match`, and `done` messages. Occasionally (aprox 1 out of 20) orders that are placed will not receive any messages from the `OrderbookSync` socket.

When an order is not sent over the socket, it will not receive even one of the message types.

During this time the socket is still connected and receiving messages, I can see the orderbook updating.

**Comment by fb55** [comment]
Assuming this has been fixed, lmk if not.
