### ISSUE TITLE
Does websocket need authentication?

### ISSUE THREAD

**Issue by nengine** [coinbase/gdax-node#116]
publicClient is working fine, but websocket is giving me CORS header ‘Access-Control-Allow-Origin’ missing error.  Any suggestion is appreciated.

**Comment by LRonHubs** [comment]
Yea what is up with this?

**Comment by nengine** [comment]
I was told that CORS headers need to be set on the resource https://ws-feed.gdax.com/ , so I think only gdax developers can do this.

**Comment by azamatsmith** [comment]
@nengine I also came across this issue, I ended up moving all of my websocket code out of the browser and to a webserver.

**Comment by LRonHubs** [comment]
Maybe I'm underslept, but the gist of these last two comments is that the library does not work, yet there are docs for it, so ppl r just gonna waste time testing code that is objectively non-functional. Cool. Maybe take out the websocket section of the tut or provide working code?

**Comment by LRonHubs** [comment]
Installing from github ( npm install coinbase/gdax-node ) fixed all the issues I was facing including the 404 error. It might be worth it to take the npm install gdax command out from the readme entirely.

**Comment by nengine** [comment]
Even after installing from coinbase/gdax-node does not work for me on the client side Vue.js app mounted inside Rails 5.1 with webpacks shown in example #1.  On the other hand, it works fine on server side express.js app as shown in example #2, #3.  May be this is what @azamatsmith saying about moving to webserver.  But ideally it should work on the client side too right?  @LRonHubs what client side app/framework you are using?

### example 1 (Vue.js client app)

```js
<template>
  <div id="trades">
    <p>{{ message }}</p>
    <button @click='load'>Load data</button>    
  </div>
</template>

<script>
  const Gdax = require('gdax');
  const publicClient = new Gdax.PublicClient();
  const websocket = new Gdax.WebsocketClient(['LTC-USD']);

  export default {
    data: function() {
      return {
        message: 'Hello from trades Vue'
      }
    },
    methods: {
      mounted: function() {
        websocket.on('message', data => {
          console.log(data);
        });    
      },

      load: function() {     
        publicClient.getProducts((error, response, data) => {
          if (error) {
            // handle the error
          } else {
            console.log(JSON.stringify(data));
          }
        });
      }
    }
  }
</script>
```


### example 2 (express.js server app)
```js
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();
const websocket = new Gdax.WebsocketClient(['LTC-USD']);

websocket.on('message', data => {
  console.log(data);
});
```

### example 3 (express.js server app)
```js
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();
const WebSocket = require('ws');

const ws = new WebSocket('wss://ws-feed.gdax.com');

ws.on('open', function open() {
  const subscribeMessage = {
      type: 'subscribe',
      product_ids: ['LTC-USD']
  };
  ws.send(JSON.stringify(subscribeMessage));

  var heartbeatMessage = {
    type: 'heartbeat',
    on: true,
  };
  ws.send(JSON.stringify(heartbeatMessage));
});

ws.on('message', function incoming(data) {
  console.log(data);
});
```

**Comment by fb55** [comment]
Right now we don't support embedding our client into web pages, so you would need to proxy all requests. This might change in the future, we don't have any immediate plans though. Closing this in favor of https://github.com/coinbase/gdax-node/issues/33

**Comment by nengine** [comment]
What did you meant to proxy all requests?  Thanks.

**Comment by CjS77** [comment]
He means you need to set up a small server (e.g. in node.js) that sits on the same machine as your browser (i.e. same vs cross-origin); then the server forwards all requests from the browser (i.e. proxies) to the GDAX api. see https://en.wikipedia.org/wiki/Same-origin_policy

**Comment by elliotaplant** [comment]
Has anyone made or found a small server that they could share? It would be nice to not have to remake it.
