### ISSUE TITLE
Orders are not sent to GDAX

### ISSUE THREAD

**Issue by sparky2708** [coinbase/gdax-node#119]
I am using authenticated client and I am calling client.sell(params, callback) or client.buy(params, callback) but no orders get submitted to gdax nor are there any errors. What might I be doing wrong?

Here is my code:

`
var Trader = function(config) {
    _.bindAll(this);

    this.post_only = true;
    this.use_sandbox = false;
    this.name = 'GDAX';
    this.import = false;
    this.scanback = false;
    this.scanbackTid = 0;
    this.scanbackResults = [];
    this.asset = config.asset;
    this.currency = config.currency;

    if(_.isObject(config)) {
        this.key = config.key;
        this.secret = config.secret;
        this.passphrase = config.passphrase;

        this.pair = [config.asset, config.currency].join('-').toUpperCase();
        this.post_only = (typeof config.post_only !== 'undefined') ? config.post_only : true;
    }

    this.gdax_public = new Gdax.PublicClient(this.pair, this.use_sandbox ? 'https://api-public.sandbox.gdax.com' : undefined);
    this.gdax = new Gdax.AuthenticatedClient(this.key, this.secret, this.passphrase, this.use_sandbox ? 'https://api-public.sandbox.gdax.com' : undefined);
}

Trader.prototype.buy = function(amount, price, callback) {
    var args = _.toArray(arguments);
    var buyParams = {
        'price': this.getMaxDecimalsNumber(price, this.currency == 'BTC' ? 5 : 2),
        'size': this.getMaxDecimalsNumber(amount),
        'product_id': this.pair,
        'post_only': this.post_only
    };

    var result = (err, data) => {
        if(err) {
            log.error('Error buying at GDAX:', err);
            return this.retry(this.buy, args);
        }
        callback(err, data.id);
    }

    log.debug('-------- SENDING (BUY) ORDER TO GDAX ------------');
    log.debug('Price: ' + buyParams.price);
    log.debug('Size: ' + buyParams.size);
    log.debug('Notional: ' + (buyParams.price * buyParams.size));
    log.debug('Product_ID: ' + buyParams.product_id);
    log.debug('Post_Only: ' + buyParams.post_only);

    this.gdax.buy(buyParams, this.normalizeResult(result));
}

Trader.prototype.getMaxDecimalsNumber = function (number, decimalLimit = 8) {
  var decimalNumber = parseFloat(number);

  // The ^-?\d*\. strips off any sign, integer portion, and decimal point
  // leaving only the decimal fraction.
  // The 0+$ strips off any trailing zeroes.
  var decimalCount = ((+decimalNumber).toString()).replace(/^-?\d*\.?|0+$/g, '').length;

  var decimalMultiplier = 1;
  for (i = 0; i < decimalLimit; i++) {
      decimalMultiplier *= 10;
  }

  return decimalCount <= decimalLimit ? decimalNumber.toString() : (Math.floor(decimalNumber * decimalMultiplier) / decimalMultiplier).toFixed(decimalLimit);
};
`

Here is my output:
`
2017-10-07 18:48:36 (DEBUG):    -------- SENDING (BUY) ORDER TO GDAX ------------
2017-10-07 18:48:36 (DEBUG):    Price: 4395
2017-10-07 18:48:36 (DEBUG):    Size: 0.11149337
2017-10-07 18:48:36 (DEBUG):    Notional: 490.01336115
2017-10-07 18:48:36 (DEBUG):    Product_ID: BTC-USD
2017-10-07 18:48:36 (DEBUG):    Post_Only: true
`

It seems the order will get submitted to gdax the first time but any subsequent orders just don’t appear on gdax and there is no error in the client.

**Comment by rmm5t** [comment]
Sorry, this doesn't sound like an issue with gdax-node. It sounds like an issue with your environment and surrounding code. Plus, it's difficult to help given the messy formatting of the original question. It's also impossible for anyone to help you given that the `normalizeResult()` function is missing from your example.  That's a tad critical given that it returns the callback function that you're trying to use.

Please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.  

@fb55 This should be safe to close.

**Comment by fb55** [comment]
Nice, thanks for flagging!
