### ISSUE TITLE
GDAX FIX API Issue

### ISSUE THREAD

**Issue by Cyral** [coinbase/gdax-node#128]
Hello, this isn't an issue with this specific repo but I am encountering something that I'd like to reach the developers.

I'm working on adding the FIX API to gdax-node which I am using for a trading bot. My bot places limit orders and cancels them as soon as the best bid/ask changes, in order to prevent the order from slipping down or up in the orderbook and taking forever to be filled.

Often times after canceling an order, I get an "Insufficient funds" error in the ExecutionReport when trying to place an order.

For example:

- Place buy order at 5000 (current best bid) for 0.01 coins
- Price gap opens
- Cancel order at 5000 (and wait for canceled message in the execution report)
- Place new order at 5000.01 for 0.01 coins
- New order is rejected for insufficient funds

It seems that I am getting the cancelled response message before the balance is actually adjusted, so I often have to try another time, or even 2-3 more times to place the orders. I'd like to be able to send my NewSingleOrder message as soon as the previous one is cancelled, but I'm likely adding extra latency by retrying the order multiple times as I always wait for a response to see if it was successful.

**Comment by davidcaseria** [comment]
Thanks for reaching out @Cyral!

Currently, balances are updated asynchronously through our clearing process which is separate from our FIX API. I agree this is a pain point for FIX API users who expect holds to be released immediately upon cancel acknowledgement. We have plans to address this issue which will transparently un-hold funds for FIX API users.

I am going to close this issue but if you experience any issues integrating the FIX API with the project feel free to reach out again. Thanks!

**Comment by lisbakke** [comment]
Hello! I was just wondering if there's any update on this since it's been 5 months or so.

What's the recommend way to deal with this from our side? Continue to resubmit orders until they go through?
