### ISSUE TITLE
Frequent disconnection from websocket API

### ISSUE THREAD

**Issue by gabrieldodan** [coinbase/gdax-node#129]
I connect to websocket API but I am disconnected frequently. I have re-connection mechanism but sometimes disconnections happens many time withing a few minutes. 

I made some tests and I have bound the ws module to a different IP, using localAddress option of ws module, still disconnection happens. If I connect to websocket API from a different server everything is ok. 

Could be a network issue between my server and API endpoint ? Anyone else encounter this issue?

Regards!

**Comment by reinierkors** [comment]
I have not encountered this issue. I have been connected for more than 8 hours straight without issues.

**Comment by gabrieldodan** [comment]
I see, thanks. Then the problem must be on my server side.
