### ISSUE TITLE
Subscribing to ticker channel via gdax web socket feed 'wss://ws-feed.gdax.com'

### ISSUE THREAD

**Issue by shannb** [coinbase/gdax-node#135]
I am attempting to subscribe to the gdax ticker channel via the websocket feed.  I specify 'ticker' as a channel name but can't seem to actually get the ticker data.  It seems to default to order book data feed ("full") instead.  I am using the following code below...

var info = {
    channels : [{"name" : "ticker"}]
    //channels : ["ticker"]
  };

  const websocket = new session.WebsocketClient(pairs,'wss://ws-feed.gdax.com',null, info);

Is there perhaps another way of specifying the channel name?  If been trying to get ticker data for hours with no success...

**Comment by jackson-sandland** [comment]
I was able to get this working today using the following object:
{
    "type": "subscribe",
    "product_ids": [
        "ETH-USD",
        "ETH-EUR"
    ],
    "channels": [
        "level2",
        "heartbeat",
        {
            "name": "ticker",
            "product_ids": [
                "ETH-BTC",
                "ETH-GBP"
            ]
        },
    ]
}

**Comment by shannb** [comment]
Interesting...

I literally just copied your object verbatim and ran it in my code... No luck.  I get the following output:

{ type: 'received',
21:23:09 web.1   |    order_id: '34ccd747-a7a3-446c-937a-9c70b64502ff',
21:23:09 web.1   |    order_type: 'limit',
21:23:09 web.1   |    size: '11.00000000',
21:23:09 web.1   |    price: '0.00739000',
21:23:09 web.1   |    side: 'sell',
21:23:09 web.1   |    client_oid: 'b1b9aa70-318d-d784-43bb-ce288c1d2bb6',
21:23:09 web.1   |    product_id: 'LTC-BTC',
21:23:09 web.1   |    sequence: 292121285,
21:23:09 web.1   |    time: '2017-11-06T02:22:50.669000Z' }

Did you do anything else in particular prior to sending that subscribe request to the exchange?

**Comment by jackson-sandland** [comment]
I'll take a look this evening - what are you using client side? If you're using React there is a simple Websocket component that may help:  https://github.com/mehmetkose/react-websocket

**Comment by kartojal** [comment]
```

**Comment by kartojal** [comment]
Mmm. I did a clean install of gdax NPM package and it does not match the github one. Checked in my node_modules directory and the source code is older than the github.

**Comment by shannb** [comment]
@kartojal I'll have to try that.  Thanks guys!

**Comment by shannb** [comment]
@kartojal  doing a fresh of coinbase/gdax-node did the trick.  Thanks!

**Comment by jmashore** [comment]
I would also like those that are wondering what the heck is going on, that I too had the same experience and had to reinstall using the code from GitHub directly
