### ISSUE TITLE
Can't receive client_oid

### ISSUE THREAD

**Issue by ThomasDolso** [coinbase/gdax-node#141]
Hello,
I'm trying to submit an order passing the "client_oid". It has a form like this:

f50ec0b7-f960-400d-91f0-c42a6d44e3d0

and it's passed as a string. I'm subscribed to the "user" channel of the websockets but the "receive" message I receive is without the "client_oid" so I don't know how to identify my order.
Inside the doc I can read "If you are consuming the public feed and see a received message with your client_oid" but I don't receive it in the "received" notification.
Any idea why? Is the above format correct?

Thanks,
Tom

**Comment by rmm5t** [comment]
I don't experience this. Here's an example payload I just pulled from the public feed:

```js
{ type: 'received',
  order_id: 'a08a91ff-74ba-456c-9f2f-924e37564a22',
  order_type: 'limit',
  size: '6.00000000',
  price: '646.56000000',
  side: 'buy',
  client_oid: 'b07a71a1-59fd-4cc5-a7d4-5b29a7644922',
  product_id: 'ETH-USD',
  sequence: 1685163807,
  time: '2017-12-13T05:07:59.963000Z' }
```

If I can get someone else's `client_oid` from the public feed, I should be able to get my own (assuming I set one).

Are you still experiencing this problem?

**Comment by ThomasDolso** [comment]
Thanks for your reply and sorry, was my fault, I figured it out
Tom

**Comment by rmm5t** [comment]
@ThomasDolso could you please close this issue?
