### ISSUE TITLE
Tx Hash through API?

### ISSUE THREAD

**Issue by LRonHubs** [coinbase/gdax-node#142]
Is it possible to get the txHash of a deposit, or txHash of a withdrawal, through the deposit and withdrawal history point of the API? This information is available on my GDAX account page but not through the API? That is sour

Transaction hash is different from deposit address. It is very very important (and standard, frankly) that both are included.

**Comment by danielebuso** [comment]
+1

**Comment by adityamertia** [comment]
I am doing this by adding to the gdax code.

Add following code @ ~/lib/clients/authenticated.js
```
getAccountTransfers(accountID, args = {}, callback) {
    if (!callback && typeof args === 'function') {
      callback = args;
      args = {};
    }
    return this.get(['accounts', accountID, 'transfers'], { qs: args }, callback);
  }

```
Call `authedClient.getAccountTransfers(account_id, callback);` this will return the list of transfers made in the account which can be used to search for txHash. Hope this helps.

**Comment by fb55** [comment]
@adityamertia Would you mind opening a PR with this?

**Comment by adityamertia** [comment]
@fb55 created a PR with the same. This will also need changes to README file to add the function description.

**Comment by rmm5t** [comment]
Closing. Support for this was added in #217.
