### ISSUE TITLE
OrderBookSync example doesn't work

### ISSUE THREAD

**Issue by KerimG** [coinbase/gdax-node#144]
The OrderbookSync example in the README

```js
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
console.log(orderbookSync.books['ETH-USD'].state());
```

doesn't return anything. It just prints out 

```
{ asks: [], bids: [] }
```

and that's it.

**Comment by KerimG** [comment]
It requires a hefty amount of time to establish the connection and to sync (in my test cases up to 5 seconds).

**Comment by rod-farva-sql** [comment]
Is that all the code you are using? I have the exact same problem except I never get anything after waiting five minutes.  Here is the code I am using..

const Gdax = require('gdax');
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
console.log(orderbookSync.books['ETH-USD'].state());

This just sits there..
{ asks: [], bids: [] }

**Comment by KerimG** [comment]
Maybe I shouldn't have closed the issue. I re-opened it and might add something to the README.

@rod-farva-sql 

Try this 

``` js
const Gdax = require('gdax');
const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
setTimeout(function() { console.log(orderbookSync.books['ETH-USD'].state()); }, 5000);
```

In retrospect, it makes sense. The Orderbook is synced asynchronously and thus by the time the example code runs console.log(), there's nothing in it.

**Comment by rod-farva-sql** [comment]
@KerimG Thank you! After about 5 seconds I'm seeing output like this below..  Now to figure out how to get the best bid and ask price out of it.
I appreciate the help!

    { id: '40420f47-9215-403e-ae34-8671db7d1920',
       side: 'buy',
       price: [Object],
       size: [Object] },
     { id: 'd12dfc36-078a-4ea3-84c4-7a4c26bc0df4',
       side: 'buy',
       price: [Object],
       size: [Object] },
     { id: 'bbc2a1ca-4372-42aa-8454-5abba31ecaff',
       side: 'buy',
       price: [Object],
       size: [Object] },
     { id: '7fc5feb3-4dfb-4da9-9d41-5fcf8844e4b6',
       side: 'buy',
       price: [Object],
       size: [Object] },
     ... 27680 more items ] }

**Comment by KerimG** [comment]
@rod-farva-sql Awesome. If you figure it out, let me know. I've got [this ](https://github.com/coinbase/gdax-node/issues/145) issue open. As you can see in your output, the "price" values are Objects. I somehow cannot get the actual price.

**Comment by rod-farva-sql** [comment]
I'll let you know if I figure it out before you.
Thanks again!

**Comment by KerimG** [comment]
@rod-farva-sql 

if you parseFloat() the values for 'price' and 'size', you'll get the number representation.

**Comment by axeldomingues** [comment]
Having the very same problem! It returns anything. It just prints out

{ asks: [], bids: [] }

**Comment by fb55** [comment]
Closing in favour of #167

**Comment by jrhea** [comment]
This is a workaround until #176 is implemented
```
var orderbookSync = new Gdax.OrderbookSync(products);
orderbookSync.on('message',data => {
  var book = orderbookSync.books['ETH-USD'].state();
  if(book.bids.length == 0 && book.asks.length == 0){
    //console.log("Waiting for data...");
  } 
  else {
    console.log(JSON.stringify(book));
  } 
});
```

**Comment by kkm** [comment]
Thanks for workround and https://docs.gdax.com/#real-time-order-book doesnt work. thanks.
