### ISSUE TITLE
How do I get the actual price value of an order? 

### ISSUE THREAD

**Issue by KerimG** [coinbase/gdax-node#145]
When calling orderbookSync.books['BTC-USD'].get('e335441b-3be7-44c8-a8ab-e196e1be2966'), I get the following data structure.

``` js { id: 'e335441b-3be7-44c8-a8ab-e196e1be2966',
  side: 'buy',
  price:
   { [String: '7092.02']
     _int: { [String: '709202'] _s: 0, _d: [Array] },
     _precision: 2 },
  size: { [String: '0.02'] _int: { [String: '2'] _s: 0, _d: [Array] }, _precision: 2 } }
```

How do I access the price as a number?  When attempting orderbookSync.books['BTC-USD'].get('e335441b-3be7-44c8-a8ab-e196e1be2966')['price'], I get 

``` js
{ [String: '7092.02']
  _int: { [String: '709202'] _s: 0, _d: [ 7, 0, 9, 2, 0, 2 ] },
  _precision: 2 }
````

**Comment by rmm5t** [comment]
The OrderBook uses the [`num`](https://github.com/defunctzombie/num) library for precision numbers. Try calling `toString()` on the price to get a human-readable value:

```js
orderbookSync.books['BTC-USD'].get(id)['price'].toString();
```

**Comment by KerimG** [comment]
>The OrderBook uses the num library for precision numbers

Thanks a bunch, @rmm5t !
