### ISSUE TITLE
v0.5.0 is missing from npm

### ISSUE THREAD

**Issue by rmm5t** [coinbase/gdax-node#148]
* [GitHub Releases](https://github.com/coinbase/gdax-node/releases) shows v0.5.0.
* [NPM](https://www.npmjs.com/package/gdax) only shows v0.4.2.

**Will a maintainer please `npm publish` v0.5.0?**

----

Known workarounds in the meantime:

`npm install coinbase/gdax-node`
or
`yarn add coinbase/gdax-node`

----

Overall, there is a lack of discipline on this project with regards to releases:

* [Haphazard and missing release notes](https://github.com/coinbase/gdax-node/releases)
* [Missing tags](https://github.com/coinbase/gdax-node/releases) for releases that are [on NPM](https://www.npmjs.com/package/gdax)
* [Missing NPM releases for tags that are on the project](https://github.com/coinbase/gdax-node/issues/148).
* [Violations of semver](https://github.com/coinbase/gdax-node/commit/b708da1bd89eb22dcf229bdd5687032f9463de6e#comments)
* Automation-wise, it's evident that neither `yarn version` nor `npm version` and `npm publish` are not used properly (nor at the same times) when actually building new releases; otherwise, the tagging and NPM publishing history wouldn't be the mess that it currently is.

----

UPDATE: There's now a v0.5.1 release on NPM (skipping v0.5.0), but this release violated semver and there's no associated tag on the repository. I think this particular issue should remain open until we fix the conventions around release management (hopefully as part of a v0.6.0 release).

**Comment by BrandonCopley** [comment]
I can help update the npm module, it's a really easy push. It wouldn't be secure, but maybe someone on Gdax could push v0.5.0 up to NPM

**Comment by rmm5t** [comment]
@BrandonCopley I've sent multiple emails to @mihar about volunteering to help maintain this project. No response in 2 weeks. 😞 

If anyone else has the keys and would like me to help maintain this project, I'm making myself available. Please feel free to review my open pull-requests on this project. Feel free to review my [GitHub open-source history](https://github.com/rmm5t) and my [StackOverflow profile](https://github.com/rmm5t) for credentials.

Here's a quick summary of what I think should be a priority for gdax-node, and I'm open to hearing other people's thoughts on the matter:

- Improve process for stable releases (including versioning, publishing, and documenting).
- Move towards a more stable v1.0 release (along with careful considerations of backwards-incompatible changes and interim releases leading up to a v1.0 release).
- Improve test coverage.
- Improve test suite build matrix for different dependency permutations (using circleci workflows or travisci matrices).
- Make the method signatures more consistent between one another.
- Most function arguments are optional or have defaults. Move toward a more consistent usage of _"keyword"_ using destructuring object parameters.
- Make the PublicClient and AuthenticatedClient more consistent between one another. Deprecate inconsistencies while providing a clean set of method signatures for moving forward.
- Make the WebsockClient more resilient. Enable the `heartbeat` channel by default, make it auto-reconnect if disconnected, etc.
- Respond to and/or clean out open Issue and Pull-Request queue.

**Comment by darthyvader** [comment]
This needs to be fixed for zenbot.

**Comment by rmm5t** [comment]
Adding a reference to my long comment about publishing minor version releases, because it's relevant to this Issue:

https://github.com/coinbase/gdax-node/pull/178#issuecomment-354144035

**Comment by rmm5t** [comment]
Closing this out. I moved the checklist I was maintaining to a wiki page:
https://github.com/coinbase/gdax-node/wiki/Project-Roadmap
