### ISSUE TITLE
promise method from sample code doesn't work

### ISSUE THREAD

**Issue by markoshust** [coinbase/gdax-node#153]
using the below script:

```
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();

publicClient
  .getProducts()
  .then(data => {
    console.log('data', data);
    // work with data
  })
  .catch(error => {
    console.log('error', error);
    // handle the error
  });
```

expected: data and error logged to console
actual: 
```
./node_modules/gdax/lib/clients/public.js:57
      throw "Must supply a callback."
      ^
```

**Comment by markoshust** [comment]
It appears the npm version of the module is out of date. i'm assuming this is not auto-published, so recommending to add a note to the readme about which version to use, as i was really wondering why the code wasn't working.

**Comment by rmm5t** [comment]
@markoshust Would you mind closing this issue in favor of consolidating the discussion under #148? There's a deeper discussion going on there.
