### ISSUE TITLE
How to retrieve transfer details?

### ISSUE THREAD

**Issue by crystalminds** [coinbase/gdax-node#155]
So when you call the following withdrawal endpoint 'withdrawals/crypto' you will get an id in the response. My guesses are that, that is the transfer id.

My question is, once you have the transfer id how can you get it's details? (E.g. Estimated Payout and Transaction Hash , etc.)

Once a withdrawal occurs I could use the transaction hash to follow it's confirmations on the blockchain, if it has 3 or more confirmations I can assume the withdrawal is complete. However it would even be better if I could call an API to poll if a withdrawal has been completed.

**Comment by fb55** [comment]
Right now this isn't possible, but I agree the feature would make a nice addition. Stay tuned :)

**Comment by kasima** [comment]
:+1: I'd find this feature useful as well.
