### ISSUE TITLE
Authed client can't get product ticker

### ISSUE THREAD

**Issue by meteorpublish** [coinbase/gdax-node#158]
The docs clearly state

> AuthenticatedClient inherits all of the API methods from PublicClient, so if you're hitting both public and private API endpoints you only need to create a single client.

But if I run `const tick = await authedClient.getProductTicker();`, I get `{ "message": "NotFound" }`.

The authedClient is created correctly because I can perform authedClient.buy() just fine.

**Comment by drootang** [comment]
Same issue using npm-installed gdax 0.4.2
