### ISSUE TITLE
Wire Transfer Not Showing Up

### ISSUE THREAD

**Issue by GreyEcologist** [coinbase/gdax-node#161]
Is there a ticket or PR someone is working on and needs help with? 

With the support team being non-existent, ill-equipped and/or incompetent, I'd love to resolve the issue myself if I can. So, if someone can point me in the right direction of what the hell is going with bank wires, I would really appreciate it.

**Comment by rmm5t** [comment]
@GreyEcologist I understand your frustration here. I'm actually in the same boat with a transfer that has been stuck for 9 days now, but this project isn't the appropriate place to vent. This is just a wrapper library around the public-facing GDAX REST API. It has no bearing on anything that might be failing on the GDAX backend.

**Comment by fb55** [comment]
Sorry, not the right place for support with transfers :/
