### ISSUE TITLE
Trying to install, what permission is missing?

### ISSUE THREAD

**Issue by MorningSleeper** [coinbase/gdax-node#163]
I get the following when I run `sudo npm install coinbase/gdax-node`

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'coinbase/gdax-node' ]
2 info using npm@5.6.0
3 info using node@v8.1.3
4 verbose npm-session 550037116ab787ee
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:coinbase/gdax-node Error while executing:
7 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/coinbase/gdax-node.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData fatal: failed to stat '.': Permission denied
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
9 verbose cwd /webserver/sites/bot
10 verbose Linux 3.13.0-135-generic
11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "coinbase/gdax-node"
12 verbose node v8.1.3
13 verbose npm  v5.6.0
14 error Error while executing:
14 error /usr/bin/git ls-remote -h -t ssh://git@github.com/coinbase/gdax-node.git
14 error
14 error fatal: failed to stat '.': Permission denied
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]

**Comment by fb55** [comment]
This doesn't seem to be an issue with this project, please try StackOverflow or similar.
