### ISSUE TITLE
Get Product Historic Rates API endpoint does not respond correctly to parameters

### ISSUE THREAD

**Issue by SpencerFishman** [coinbase/gdax-node#168]
I am using the following code snippet to test out the Public GDAX API, specifically the historic rates endpoint. As you can see, the start/end time difference is precisely 50 minutes:

	'use strict';
	const Gdax = require('gdax');
	const publicClient = new Gdax.PublicClient();

	(async () => {
		try {
			let d = new Date();

			let params = {
				'start': (new Date(d.getTime() - 1000 * 60 * 50)).toISOString(),
				'end': d.toISOString(),
				'granularity': 600
			};

			const hr = await publicClient.getProductHistoricRates(params);
			console.log(hr.length);

		} catch(error) {
			console.log("error: ", error);
		}
	}) ();

When granularity is set to 600 seconds, which is 10 minutes, the code behaves PERFECTLY and the output is `Granules polled:  6`. However when granularity is set to 300 seconds, which is 5 minutes, the code outputs `Granules polled:  401`. If I bump the interval to 30 minutes, or 1800 seconds, the code outputs `Granules polled:  399`.

The API is NOT behaving correctly.

**Comment by tkriplean** [comment]
I have also been noticing odd results for the past week or so, ever since GDAX came back online for maintenance.

I tested out @SpencerFishman's script above, and I basically get all kinds of results for any granularity I set, including 600 seconds. I don't think any granularity is working as expected.

**Comment by tkriplean** [comment]
And this also appears to be a problem with node-gdax, not the GDAX API itself. I get correct results when querying directly. E.g.: 

https://api.gdax.com/products/BTC-USD/candles?start=2017-12-21T20:51:03.932Z&end=2017-12-21T21:41:03.932Z&granularity=300

**Comment by tkriplean** [comment]
I've been testing this problem a bit more. I'm comparing results from (1) accessing candle data via node-gdax, (2) using the Request library directly, and (3) from directly accessing the REST API on GDAX. 

What I'm seeing is that the node-gdax, Request, and direct access are generally returning the same data, but that data is often incorrect. I think the GDAX API is not performing well right now, either from new bugs or difficulty scaling with increased load in the past several days. It also means that this probably not a gdax-node issue, though gdax-node could do a lot more to detect these data integrity issues and alert programmers.

If you want to do your own testing:

Here is the request that gets assembled from node-gdax:

```
const request = require('request')
request({ 
    qs: { 
      start: '2017-12-15T00:27:52.233Z',
      end: '2017-12-21T22:17:52.233Z',
      granularity: granularity 
    },
    method: 'GET',
    uri: 'https://api.gdax.com/products/BTC-USD/candles',
    headers: { 
       'User-Agent': 'gdax-node-client',
       Accept: 'application/json',
       'Content-Type': 'application/json' 
    } 
  }, function(a,b,data){
      //console.log(data)
      console.log('Granules from direct request', JSON.parse(data).length)
  })
````

The corresponding url you can use directly in the web browser is: https://api.gdax.com/products/BTC-USD/candles?start=2017-12-16T00%3A27%3A52.233Z&end=2017-12-21T22%3A17%3A52.233Z&granularity=3600

**Comment by fb55** [comment]
Our candles endpoint was acting up recently, which has been fixed. The initial issue of too many candles being returned for certain intervals is still valid, but not related to this project.

**Comment by mbana** [comment]
Hi,

Why was this closed? Is it because it is going to be fixed in the backend. Either way, it would be nice to monitor the status of this.
