### ISSUE TITLE
Question: get crypto deposit address via API

### ISSUE THREAD

**Issue by sagivo** [coinbase/gdax-node#172]
I didn't find any way to deposit crypto via api. is there a way to generate/retrieve my deposit crypto address?

**Comment by rmm5t** [comment]
Dupe of #91. 

As a workaround, until something is implemented more directly, see https://github.com/coinbase/gdax-node/issues/91#issuecomment-352441654

**Comment by sagivo** [comment]
thanks @rmm5t 
closing dup.
