### ISSUE TITLE
Websocket Data Issues

### ISSUE THREAD

**Issue by ccravens** [coinbase/gdax-node#173]
This is more of a websocket data issue than an API/library issue.

I noticed that when I subscribe to the authenticated websocket channel, it seems that I am not receiving all of the price updates. I compare the price I am getting through websockets, for example BTC/USD,  with the website and about 80% of the time the quotes are mis-matched. Even worse, many times the price through the websocket channel will get cut in half for a few seconds and then return back to normal! For example, BTC is trading at ~14K USD right now, but sometimes I get a price of 7K for a few seconds. This is how I'm getting the price:

```javascript
const websocket = new Gdax.WebsocketClient(
  ['BTC-USD'],
  'wss://ws-feed.gdax.com',
  {
    key: 'mykey',
    secret: 'mysecret',
    passphrase: 'mypass',
  },
  { heartbeat: true }
);


websocket.on('message', data => {
  if(data.product_id === 'BTC-USD' && data.reason === 'filled' && typeof(data.price) !== 'undefined') {
    btcusd = data.price; // Never up to date with website price, sometimes is cut in half
  }
});
```
Am I doing this right? I'm thinking maybe I'm missing a configuration option? Any guidance is much appreciated, thanks!

**Comment by fb55** [comment]
The website is just a normal consumer of the websocket feed, there should never be any difference in behaviour. Perhaps try checking the `type` of messages as well.

**Comment by ccravens** [comment]
@fb55 Thank you for your feedback. We have looked at the type and we can get one of the following types:
[received,open,done,match]

as you can see in the example above, we get the price for ALL types, and we assume that the current price of BTC is based on filled orders (reason === 'filled').

We have not made any updates to our code and realized that the issue with the price being cut in half is no longer coming up. There is not any reference to this in either the GDAZ API docs or the docs for this library
