### ISSUE TITLE
"Failed to subscribe" breaks all books within OrderbookSync

### ISSUE THREAD

**Issue by ivoputzer** [coinbase/gdax-node#174]
It looks like that when trying to initialise a multi-product orderbook, non of the feeds are dispatched when one of the books responds with:

```javascript
{type: 'error', message: 'Failed to subscribe', reason: 'Invalid product ID provided'}
```

Is there a way to handle this kind of behaviour other than initialising one orderbook per product_id and handle exactly this error message?

**Comment by fb55** [comment]
This is not the book, but the feed responding with an error. This results in the subscribe call being ignored entirely, so please ensure all passed product ids are valid (https://api.gdax.com/products should have an entry for it).
