### ISSUE TITLE
Question: get multiple markets in one call

### ISSUE THREAD

**Issue by sagivo** [coinbase/gdax-node#175]
is there a way to get all tickers (BTC, ETH, LTC...) in one call? 
in most of the other exchanges, it's pretty straight forward.

**Comment by fb55** [comment]
There isn't a combined API call right now. We might want to add one in the future, for now every product needs to be queried separately.

**Comment by Berone** [comment]
Can you create this functionality?

**Comment by laviua** [comment]
any updates?

**Comment by patrickjm** [comment]
I want to get all the product tickers at once, and I get rate limited when I poll everything. Is there a better solution that putting sleeps in my code?
