### ISSUE TITLE
ProductID on getProductOrderBook overridden by default PublicClient.ProductID

### ISSUE THREAD

**Issue by ManickYoj** [coinbase/gdax-node#182]
When using the `getProductOrderBook` method of `PublicClient`, the response always makes use of the [`PublicClient.productID`](https://github.com/coinbase/gdax-node/blob/master/lib/clients/public.js#L6) ('BTC-USD') rather than use any the argument passed to the productID parameter of the method.

### Replication:
Both of the following lines, despite different productID parameters, will return the SAME result: that for the `PublicClient.productID`, IE 'BTC-USD' (counter to the instructions in the README).
```
publicClient.getProductOrderBook('BTC-USD', (error, response, book) => {console.log(book) });
=> { sequence: 4701373790, bids: [ [ '14580', '2.55392861', 14 ] ], asks: [ [ '14580.01', '9.33786435', 7 ] ] }
// Okay

publicClient.getProductOrderBook('LTC-BTC', (error, response, book) => {console.log(book) });
=> { sequence: 4701373790, bids: [ [ '14580', '2.55392861', 14 ] ], asks: [ [ '14580.01', '9.33786435', 7 ] ] }
// WTF??
```

If we set the `PublicClient.productID` before each line, then they will return the expected result. I'm using this as a workaround at present, but I get pretty upset when I follow README instructions that straight up don't work.
```
publicClient.productID = 'BTC-USD'
publicClient.getProductOrderBook('BTC-USD', (error, response, book) => {console.log(book) });
=> { sequence: 4701373790, bids: [ [ '14580', '2.55392861', 14 ] ], asks: [ [ '14580.01', '9.33786435', 7 ] ] }

publicClient.productID = 'LTC-BTC'
publicClient.getProductOrderBook('LTC-BTC', (error, response, book) => {console.log(book) });
{ sequence: 360636631, bids: [ [ '0.01703', '595.12056327', 48 ] ], asks: [ [ '0.01704', '226.653572', 25 ] ] }
```

I assume this is probably a scoping issue, but someone better with JS than I could confirm.

**Comment by rmm5t** [comment]
@ManickYoj It sounds like you're not using the latest version in the `master` branch.

> _despite different productID parameters, will return the SAME result_

The [test suite](https://github.com/coinbase/gdax-node/blob/master/tests/public_client.spec.js#L29-L57) proves otherwise, and here's the behavior that I see.
```
> client.getProductOrderBook('BTC-USD', (error, response, book) => {console.log(book) });
> { sequence: 4704924388,
  bids: [ [ '14519.99', '5.42405078', 36 ] ],
  asks: [ [ '14520', '0.33616341', 5 ] ] }

> client.getProductOrderBook('LTC-USD', (error, response, book) => {console.log(book) });
> { sequence: 1044559356,
  bids: [ [ '245.76', '1636.48541679', 18 ] ],
  asks: [ [ '245.77', '180.19602585', 10 ] ] }
```

**Please be sure to upgrade your gdax dependency.**

```
npm install coinbase/gdax-node

# or

yarn add coinbase/gdax-node
```

**This is also related to not having the latest versions published on NPM at the moment**. Please feel free to chime in on the discussion in #148.

If the above fixes your issue, please feel free to close; otherwise, please provide additional information.

**Comment by rmm5t** [comment]
> but I get pretty upset when I follow README instructions that straight up don't work.

Aside, I understand that you were frustrated, but please take your anger elsewhere. I personally work on this project with **zero compensation**.  This is an open source wrapper library that you have **free** license to use. 

>  this is probably a scoping issue, but someone better with JS than I could confirm

I get it. Debugging can be hard, but please don't first assume that a problem is someone else's fault before you fully understand the issue yourself.

❤️

**Comment by ManickYoj** [comment]
Fair - followed the `npm install gdax` instruction on the README to install.

Upset was the wrong word. Frustrated was a better choice, and it was with the code, not the maintainers. I understand open source is open source and I do appreciate your work.

Thanks for the swift response.
