### ISSUE TITLE
Add support for channel subscriptions over websocket

### ISSUE THREAD

**Issue by ConnorChristie** [coinbase/gdax-node#185]
The GDAX API allows subscribing to specific channels instead of getting the default channel. It would be nice if we had the option to specify the channel ourselves through this interface.

**Comment by rmm5t** [comment]
> _It would be nice if we had the option to specify the channel ourselves through this interface._

**You do have that option:**

```bash
npm install coinbase/gdax-node
```

```js
const GDAX = require('gdax');

//...
const auth = { key, secret, passphrase }; // or undefined
const channels = ['ticker', 'user', 'matches', 'level2', 'full']; // all your possible options
const websocket = new GDAX.WebsocketClient(
  ['BTC-USD'],
  undefined,
  auth,
  { channels }
); // heartbeat channel is automatically subscribed
```

---

**The README is waiting on #179 to get merged in to capture that piece of documentation.**

**Comment by ConnorChristie** [comment]
Perfect, thanks for that information!

**Comment by rmm5t** [comment]
No problem. Would you mind closing this issue?

**Comment by TriangleIL** [comment]
Does this actually work?  I've tried the exact snippet above, and I can't seem to get any data from the API other than message types: 
`'open', 'match', 'done' and 'received'`

I never see the 'subscriptions' message from GDAX confirming my channels.  I also don't see the 'ticker' messages coming through...
