### ISSUE TITLE
Is there a way to measure API latency?

### ISSUE THREAD

**Issue by tebuevd** [coinbase/gdax-node#187]
Is there a way to measure the current latency of the API (as it is reported on status.gdax.com)? Ideally I'd like to not place orders when the latency is greater than 100ms.

Thanks

**Comment by rmm5t** [comment]
## Short Story: 

No. The [REST API](https://docs.gdax.com/#api) doesn't expose this specific information.

## Medium Story (Option 1):

StatusPage (the platform that GDAX uses for it's status page), does expose some JSON endpoints for its pages. For example: 

* https://status.gdax.com/index.json
* https://status.gdax.com/metrics-display/81k8r4b0w43k/day.json

## Medium Story (Option 2):

You perhaps can better glean something from [the `/time` endpoint](https://docs.gdax.com/#time) (and how that server time differs from your known client time). This endpoint isn't specifically exposed in this wrapper library, but you can still access it like so:

```js
> client.get(['time']).then((time) => console.log(time))
Promise { <pending> }
> { iso: '2017-12-30T18:44:35.025Z', epoch: 1514659475.025 }
```

## Long Story:

https://status.gdax.com/ is displaying _average_ response time, not latency. Those are potentially two very different things. Latency is very dependent up on where the client is located in relation to the server. 

It's not immediately clear exactly what the response time on the GDAX Status page is measuring. It could be the average response time from a known monitoring client (likely), or it could be the result of metrics directly from the server's own analytics. Either way, it's still representing an average response time. Certain API endpoints might be faster than others during times of peak load. 

My point is that the status page (or any other external metric) might not be what your looking for. What really matters is your specific measured response time from your live client. You'd be better to wrap your own API calls with a timer and make decisions based on that. e.g. Once the average resopnse time of, say, the last 10 API calls that you made have risen above your acceptable threshold, perhaps, you halt trading, but continue to place other occasional API calls to measure the response until your happy again.

**Comment by tebuevd** [comment]
Thank you so much for such a detailed answer! I run my bot on AWS us-east-1 (hence as close to GDAX as possible), but had a lot of trouble earlier today when REST API performance issues manifested (API calls timing out, orders being executed on older price information etc.) 

Plan right now is to measure response times for every order I place and ping for /time a few times a second when I'm not placing orders.

**Comment by rmm5t** [comment]
You're very welcome. Please feel free to close this issue out.

> _and ping for /time a few times a second_

That's probably a bit excessive, but ¯\_(ツ)_/¯
