### ISSUE TITLE
gdax - whitelist ipv6 address

### ISSUE THREAD

**Issue by mbana** [coinbase/gdax-node#188]
I've tried to add an ipv6 address via the gdax UI and it didn't work so I am wondering if it is whitelisting an ipv6 address is allowed, and if whitelisting multiple addresses are allowed. The latter saves me having to create new keys for each addresss.

Using an ipv4 address works fine.

**Comment by rmm5t** [comment]
Whitelisting multiple IP Addresses with the same API key is not currently supported. See #152.

Regarding IPv6, someone from the GDAX team is going to have to chime in about that.

/cc @fb55 @mihar

**Comment by a--hoang** [comment]
IPv6 addresses should be supported. @mbana are you still unable to whitelist?

We do not support multiple IP address whitelisting at this time.

**Comment by rmm5t** [comment]
Closing this out due to lack of follow-up. Please feel free to chime in again if you're still having trouble whitelisting a single IPv6 address.

Supporting multiple IP addresses is likely outside the scope of this particular discussion on the gdax-node repository.
