### ISSUE TITLE
Connection closed...

### ISSUE THREAD

**Issue by MMrj9** [coinbase/gdax-node#193]
Everything was working fine and a few days ago it stopped working for no reason. I already tried to use the last version but the problem persists.

Ex:   
```
authedClient.getOrders(function(err, response, data) {
      console.log(response);
})
```

err and data are null. 

Response:

> IncomingMessage {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: 
   { end: [ [Function: responseOnEnd], [Function] ],
     close: [ [Function], [Function] ],
     data: [Function],
     error: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  socket: 
   TLSSocket {
     _tlsOptions: 
      { pipe: null,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: false,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: [Object],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener] },
     _eventsCount: 9,
     connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'api.gdax.com',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     destroyed: true,
     _bytesDispatched: 334,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     parser: null,
     _httpMessage: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'GET /orders HTTP/1.1\r\nUser-Agent: gdax-node-client\r\nAccept: application/json\r\nContent-Type: application/json\r\nCB-ACCESS-KEY: a40d5f702b0d10c3722af927ad01838f\r\nCB-ACCESS-SIGN: YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=\r\nCB-ACCESS-TIMESTAMP: 1514914365.391\r\nCB-ACCESS-PASSPHRASE: ttjqqga4bgk\r\nhost: api.gdax.com\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/orders',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     read: [Function],
     _consuming: true,
     _idleNext: null,
     _idlePrev: null,
     _idleTimeout: -1 },
  connection: 
   TLSSocket {
     _tlsOptions: 
      { pipe: null,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: false,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: [Object],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener] },
     _eventsCount: 9,
     connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'api.gdax.com',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     destroyed: true,
     _bytesDispatched: 334,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     parser: null,
     _httpMessage: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'GET /orders HTTP/1.1\r\nUser-Agent: gdax-node-client\r\nAccept: application/json\r\nContent-Type: application/json\r\nCB-ACCESS-KEY: a40d5f702b0d10c3722af927ad01838f\r\nCB-ACCESS-SIGN: YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=\r\nCB-ACCESS-TIMESTAMP: 1514914365.391\r\nCB-ACCESS-PASSPHRASE: ttjqqga4bgk\r\nhost: api.gdax.com\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/orders',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     read: [Function],
     _consuming: true,
     _idleNext: null,
     _idlePrev: null,
     _idleTimeout: -1 },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: true,
  headers: 
   { date: 'Tue, 02 Jan 2018 17:32:46 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '2',
     connection: 'close',
     'set-cookie': [ '__cfduid=df440e8ca5c8f70e851a5dbdf3a039dc51514914366; expires=Wed, 02-Jan-19 17:32:46 GMT; path=/; domain=.gdax.com; HttpOnly' ],
     'access-control-allow-headers': 'Content-Type, Accept, cb-session, cb-fp',
     'access-control-allow-methods': 'GET,POST,DELETE,PUT',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'cb-before, cb-after',
     'access-control-max-age': '7200',
     etag: 'W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"',
     'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
     'x-content-type-options': 'nosniff',
     server: 'cloudflare-nginx',
     'cf-ray': '3d6f75a46a926212-LIS' },
  rawHeaders: 
   [ 'Date',
     'Tue, 02 Jan 2018 17:32:46 GMT',
     'Content-Type',
     'application/json; charset=utf-8',
     'Content-Length',
     '2',
     'Connection',
     'close',
     'Set-Cookie',
     '__cfduid=df440e8ca5c8f70e851a5dbdf3a039dc51514914366; expires=Wed, 02-Jan-19 17:32:46 GMT; path=/; domain=.gdax.com; HttpOnly',
     'Access-Control-Allow-Headers',
     'Content-Type, Accept, cb-session, cb-fp',
     'Access-Control-Allow-Methods',
     'GET,POST,DELETE,PUT',
     'Access-Control-Allow-Origin',
     '*',
     'Access-Control-Expose-Headers',
     'cb-before, cb-after',
     'Access-Control-Max-Age',
     '7200',
     'ETag',
     'W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"',
     'Strict-Transport-Security',
     'max-age=15552000; includeSubDomains; preload',
     'X-Content-Type-Options',
     'nosniff',
     'Server',
     'cloudflare-nginx',
     'CF-RAY',
     '3d6f75a46a926212-LIS' ],
  trailers: {},
  rawTrailers: [],
  upgrade: false,
  url: '',
  method: null,
  statusCode: 200,
  statusMessage: 'OK',
  client: 
   TLSSocket {
     _tlsOptions: 
      { pipe: null,
        secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: false,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: [Object],
        end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        free: [Function: onFree],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        error: [Function: socketErrorListener] },
     _eventsCount: 9,
     connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'api.gdax.com',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     destroyed: true,
     _bytesDispatched: 334,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     parser: null,
     _httpMessage: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'GET /orders HTTP/1.1\r\nUser-Agent: gdax-node-client\r\nAccept: application/json\r\nContent-Type: application/json\r\nCB-ACCESS-KEY: a40d5f702b0d10c3722af927ad01838f\r\nCB-ACCESS-SIGN: YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=\r\nCB-ACCESS-TIMESTAMP: 1514914365.391\r\nCB-ACCESS-PASSPHRASE: ttjqqga4bgk\r\nhost: api.gdax.com\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/orders',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     read: [Function],
     _consuming: true,
     _idleNext: null,
     _idlePrev: null,
     _idleTimeout: -1 },
  _consuming: true,
  _dumped: false,
  req: 
   ClientRequest {
     domain: null,
     _events: 
      { socket: [Object],
        response: [Function: bound ],
        error: [Function: bound ],
        drain: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedHeader: {},
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.gdax.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 334,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.gdax.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 334,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _header: 'GET /orders HTTP/1.1\r\nUser-Agent: gdax-node-client\r\nAccept: application/json\r\nContent-Type: application/json\r\nCB-ACCESS-KEY: a40d5f702b0d10c3722af927ad01838f\r\nCB-ACCESS-SIGN: YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=\r\nCB-ACCESS-TIMESTAMP: 1514914365.391\r\nCB-ACCESS-PASSPHRASE: ttjqqga4bgk\r\nhost: api.gdax.com\r\nConnection: close\r\n\r\n',
     _headers: 
      { 'user-agent': 'gdax-node-client',
        accept: 'application/json',
        'content-type': 'application/json',
        'cb-access-key': 'a40d5f702b0d10c3722af927ad01838f',
        'cb-access-sign': 'YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=',
        'cb-access-timestamp': 1514914365.391,
        'cb-access-passphrase': 'ttjqqga4bgk',
        host: 'api.gdax.com' },
     _headerNames: 
      { 'user-agent': 'User-Agent',
        accept: 'Accept',
        'content-type': 'Content-Type',
        'cb-access-key': 'CB-ACCESS-KEY',
        'cb-access-sign': 'CB-ACCESS-SIGN',
        'cb-access-timestamp': 'CB-ACCESS-TIMESTAMP',
        'cb-access-passphrase': 'CB-ACCESS-PASSPHRASE',
        host: 'host' },
     _onPendingData: null,
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/orders',
     _ended: true,
     res: [Circular],
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null },
  request: 
   Request {
     domain: null,
     _events: 
      { error: [Function: bound ],
        complete: [Function: bound ],
        pipe: [Function],
        data: [Function],
        end: [Function] },
     _eventsCount: 5,
     _maxListeners: undefined,
     headers: 
      { 'User-Agent': 'gdax-node-client',
        Accept: 'application/json',
        'Content-Type': 'application/json',
        'CB-ACCESS-KEY': 'a40d5f702b0d10c3722af927ad01838f',
        'CB-ACCESS-SIGN': 'YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=',
        'CB-ACCESS-TIMESTAMP': 1514914365.391,
        'CB-ACCESS-PASSPHRASE': 'ttjqqga4bgk' },
     method: 'GET',
     uri: 
      Url {
        protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'api.gdax.com',
        port: 443,
        hostname: 'api.gdax.com',
        hash: null,
        search: null,
        query: null,
        pathname: '/orders',
        path: '/orders',
        href: 'https://api.gdax.com/orders' },
     qsStringifyOptions: { arrayFormat: 'repeat', format: 'RFC3986' },
     callback: [Function],
     readable: true,
     writable: true,
     explicitMethod: true,
     _qs: 
      Querystring {
        request: [Circular],
        lib: [Object],
        useQuerystring: undefined,
        parseOptions: {},
        stringifyOptions: [Object] },
     _auth: 
      Auth {
        request: [Circular],
        hasAuth: false,
        sentAuth: false,
        bearerToken: null,
        user: null,
        pass: null },
     _oauth: OAuth { request: [Circular], params: null },
     _multipart: 
      Multipart {
        request: [Circular],
        boundary: 'f64ced3c-9894-422e-a916-d56c0a43f401',
        chunked: false,
        body: null },
     _redirect: 
      Redirect {
        request: [Circular],
        followRedirect: true,
        followRedirects: true,
        followAllRedirects: false,
        followOriginalHttpMethod: false,
        allowRedirect: [Function],
        maxRedirects: 10,
        redirects: [],
        redirectsFollowed: 0,
        removeRefererHeader: false },
     _tunnel: 
      Tunnel {
        request: [Circular],
        proxyHeaderWhiteList: [Object],
        proxyHeaderExclusiveList: [] },
     setHeader: [Function],
     hasHeader: [Function],
     getHeader: [Function],
     removeHeader: [Function],
     localAddress: undefined,
     pool: {},
     dests: [],
     __isRequestRequest: true,
     _callback: [Function],
     proxy: null,
     tunnel: true,
     setHost: true,
     originalCookieHeader: undefined,
     _disableCookies: true,
     _jar: undefined,
     port: 443,
     host: 'api.gdax.com',
     path: '/orders',
     httpModule: 
      { Server: [Object],
        createServer: [Function: createServer],
        globalAgent: [Object],
        Agent: [Object],
        request: [Function: request],
        get: [Function: get] },
     agentClass: { [Function: Agent] super_: [Object] },
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     _started: true,
     href: 'https://api.gdax.com/orders',
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /orders HTTP/1.1\r\nUser-Agent: gdax-node-client\r\nAccept: application/json\r\nContent-Type: application/json\r\nCB-ACCESS-KEY: a40d5f702b0d10c3722af927ad01838f\r\nCB-ACCESS-SIGN: YzCclCHTxVFR+6bd9eFyF+OoWsiAJwE7gNC2426mKgc=\r\nCB-ACCESS-TIMESTAMP: 1514914365.391\r\nCB-ACCESS-PASSPHRASE: ttjqqga4bgk\r\nhost: api.gdax.com\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/orders',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     ntick: true,
     response: [Circular],
     originalHost: 'api.gdax.com',
     originalHostHeaderName: 'host',
     responseContent: [Circular],
     _destdata: true,
     _ended: true,
     _callbackCalled: true },
  toJSON: [Function: responseToJSON],
  caseless: 
   Caseless {
     dict: 
      { date: 'Tue, 02 Jan 2018 17:32:46 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '2',
        connection: 'close',
        'set-cookie': [Object],
        'access-control-allow-headers': 'Content-Type, Accept, cb-session, cb-fp',
        'access-control-allow-methods': 'GET,POST,DELETE,PUT',
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'cb-before, cb-after',
        'access-control-max-age': '7200',
        etag: 'W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"',
        'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
        'x-content-type-options': 'nosniff',
        server: 'cloudflare-nginx',
        'cf-ray': '3d6f75a46a926212-LIS' } },
  read: [Function],
  body: '[]' }

**Comment by rmm5t** [comment]
Be careful, **you just exposed your GDAX API Key and Passphrase.**

---

> err and data are null.

Based on your dump of `response`, that doesn't appear to be true:

> `body: '[]' }`

`data` just looks to be an empty array.

---

I cannot reproduce what you're claiming.

```js
client.getOrders({ product_id: 'BTC-USD', status: 'open' }, (err, resp, data) => console.log(data));
> [ { id: '{hidden}',
    price: '20000.00000000',
    size: '0.00100000',
    product_id: 'BTC-USD',
    side: 'sell',
    stp: 'dc',
    type: 'limit',
    time_in_force: 'GTC',
    post_only: true,
    created_at: '2018-01-02T15:47:37.151183Z',
    fill_fees: '0.0000000000000000',
    filled_size: '0.00000000',
    executed_value: '0.0000000000000000',
    status: 'open',
    settled: false } ]
```
