### ISSUE TITLE
publicClient.getProductHistoricRates('BTC-USD', { granularity: 3000 }, callback); ... callback not a function

### ISSUE THREAD

**Issue by DevStormUK** [coinbase/gdax-node#194]
I've attempted to use:

publicClient.getProductHistoricRates('BTC-USD', { granularity: 3000 }, callback);

//here is my code:
```
publicClient.getProductHistoricRates('BTC-USD', {granularity: 3000} ,function(err,res,rates){
    if(err){return console.log(err)}

    console.log(rates);
});
```

and I'm getting a **TypeError**: **callback is not a function**

```
......./node_modules/gdax/lib/clients/public.js:45
callback(err, response, data);
^
```
 
The getProductHistoricRates('BTC-USD', callback); method on the publicClient works when the {granularity : 3000} is **omitted**.

...my node_module.gdax/lib/clients/public.js:45 contains the following code

```
prototype.makeRequestCallback = function(callback) {
     return function(err, response, data) {
       try {
         data = JSON.parse(data);
       } catch (e) {
         data = null
       }
       callback(err, response, data);        // line 45
     };
};
```

**Comment by rmm5t** [comment]
Your first code example (currently) requires that you're using the `master` branch.

```
npm install coinbase/gdax-node
```

See #148 for more information and chime in there to help get new versions published.

(Please close if this resolves your issue.)
