### ISSUE TITLE
paging: API requires next/previous cursor value

### ISSUE THREAD

**Issue by jkuchar** [coinbase/gdax-node#195]
...but no such value is provided though gdax-node.

For example, when I need to list all fills there is noway how to do that, because there is now way how to get an next/previous cursor number. This will be issue probably for all other paging-enable endpoints.

**Comment by rmm5t** [comment]
My guess is that you're using promises. The object returned by a fulfilled promise doesn't contain any of the `response` data (and thereby the header data necessary to pull the `cb-after` header).

However, depending on your particular API call, you can still glean the same value by looking at the last object in the array of the paged data.

**For example, if you were trying to get the next `after` value for fills**:

```js
client.getFills({ product_id: 'LTC-USD' }).then((fills) => {
  const lastFill = fills.length > 0 && fills[fills.length - 1];
  const after = lastFill.trade_id; // Use this on your next paginated request as the `after` param
  console.log(after) // => 12345
});
```

---

**Alternatively, you can use the callback signature and pull the headers from the `response`.**

```js
client.getFills({ product_id: 'LTC-USD' }, (err, response, fills) => {
  const after = response.headers['cb-after'];
  console.log(after); // => 12345
});
```

**Comment by jkuchar** [comment]
Hmm, I didn't expected this to be so low-level.
