### ISSUE TITLE
getFills: update typescript signature

### ISSUE THREAD

**Issue by jkuchar** [coinbase/gdax-node#196]
There is noway how to specify product/orderId (which is supported by the API) for getFills() method because there is only PageArgs arguments type.

**Comment by rmm5t** [comment]
A pull-request is very much welcome here.

---

\<rant> Ugh, TypeScript is such a disaster, and far too limiting for a wrapper library around changing RESTful APIs. It pretty much guarantees forwards compatibility issues. \</rant>

**Comment by fb55** [comment]
Fixed on master
