### ISSUE TITLE
Unhandled promise rejection (rejection id: 2): TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by JBaczuk** [coinbase/gdax-node#197]
When calling:

```
authedClient.getFills()
            .then(fills => {
              resolve(fills)
            })
            .catch(error => {
              console.error('error: ' + error)
            })
```
I'm getting the following error:
`Unhandled promise rejection (rejection id: 2): TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.`

**Comment by rmm5t** [comment]
Cannot reproduce:

```js
client.getFills().then(console.log).catch(console.log)
// [ { created_at: '2018-01-02T18:34:34.501Z',
//    trade_id: 12345678,
//    product_id: 'BTC-USD',
//    ...
```

---

Please make sure you're using the latest version in the `master`  branch.  

```
npm install coinbase/gdax-node
```

See #148 for more information and to chime in on a deeper discussion about versioning.

---

(please close if this resolves your issuel; otherwise, please supply more information)

**Comment by JBaczuk** [comment]
Ok let me take a closer look...

**Comment by JBaczuk** [comment]
Ok, I'm closing this issue, as it was an issue with node.js `process.env.GDAX_KEY` was returning undefined, even though it was defined.  I had to set the environment variables again, and then it was defined in the node application.

**Comment by eimajenthat** [comment]
Leaving a note here in case someone Google brings someone else here having the same problem as me.  I'm executing my script with a cron job, which doesn't process .env for reasons I don't yet understand.  Found an easy fix here: https://stackoverflow.com/a/50916902/1004008
