### ISSUE TITLE
issue with the candles API

### ISSUE THREAD

**Issue by adityamertia** [coinbase/gdax-node#204]
Hi,
I am trying to fetch candles(1min) data from API as follow:
```
var date = new Date();
var endTs = date.toISOString();
var startTs = new Date(date.getTime()-900000).toISOString();
var params = {
    start: startTs,
    //start: "2018-01-06T13:45:08.130Z",
    end: endTs,
    //end: "2018-01-06T14:00:08.130Z",
    granularity: 60
};
publicClient.getProductHistoricRates('ETH-USD', params, function(err,resp){
        console.log(resp.body);
        console.log(JSON.parse(resp.body).length);
});
```
The above works if the start and end values are hardcoded(commented code above).
But if i get the current time and get the 15min(900secs) older time and use them as variables, it doesn't work.
Can anyone help out with the issue?

**Comment by rmm5t** [comment]
Hi @adityamertia,  As far as I know, the calculated candlestick data is not available in the websocket feed; however, if you're interested in chart data as frequent as 1 min, just monitor the `ticker` channel and build a candlestick for each minute. You could even make the current minute's candlestick update  in real-time.

**Comment by rmm5t** [comment]
**What doesn't work?** I just tried your exact code, and I got the expected output

```
[
  [1515264780,994.5,994.5,994.5,994.5,14.697630010000001],
  [1515264720,994.49,994.5,994.5,994.5,22.028889700000004],
  [1515264660,994.49,994.5,994.5,994.5,46.355845990000006],
  [1515264600,994.49,994.5,994.5,994.5,76.7489278],
  ...
```

**Comment by adityamertia** [comment]
The code pasted above (run as is ) will work and will generate 350 entries which doesnt respect the granularity of 60 sec and start and end time of 15min apart.
However just use the below code instead:
```
var date = new Date();
var endTs = date.toISOString();
var startTs = new Date(date.getTime()-900000).toISOString();
var params = {
    //start: startTs,
    start: "2018-01-06T13:45:08.130Z",
    //end: endTs,
    end: "2018-01-06T14:00:08.130Z",
    granularity: 60
};
publicClient.getProductHistoricRates('ETH-USD', params, function(err,resp){
        console.log(resp.body);
        console.log(JSON.parse(resp.body).length);
});
```
This will result in expected output i.e. 15 entries of 1 minute candlestick for a start/end difference of 15 min.
What i have done is just used hardcoded timestamp values.

**Comment by rmm5t** [comment]
### Please read the docs: 

 https://docs.gdax.com/#get-historic-rates

> _If data points are readily available, **your response may contain as many as 350 candles and some of those candles may precede your declared start value**._

(please close this issue)
