### ISSUE TITLE
gdax node_module gets automatically deleted

### ISSUE THREAD

**Issue by adityamertia** [coinbase/gdax-node#206]
Hi,
I am not sure if anyone faced a similar issue and it is kind of weird issue. Sometimes the gdax node_module  installed using `npm install coinbase/gdax-node --save` gets automatically deleted from the node_modules after an arbitrary time. There is no trace of any command/cron running that would delete the same. 
When i run the app that includes gdax module, app throws error saying gdax not found.
If someone else has faced a similar issue pls let me know.

**Comment by rmm5t** [comment]
This clearly isn't related to this project. 

Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.
