### ISSUE TITLE
BaseOrderInfo types

### ISSUE THREAD

**Issue by brunoscopelliti** [coinbase/gdax-node#207]
The types of [`BaseOrderInfo` interface](https://github.com/coinbase/gdax-node/blob/master/index.d.ts#L50-L65) does not match my experience...

For example `price`, `size`, and other properties which are defined as `number`, at runtime are `string`. Is this a bug in the type definition file, or is there any reason for this?

**Comment by rmm5t** [comment]
Looks like a bug in the type definition file.

**Comment by brunoscopelliti** [comment]
I will attempt a fix tomorrow, thanks.
