### ISSUE TITLE
APIs requests don't error out

### ISSUE THREAD

**Issue by itajaja** [coinbase/gdax-node#208]
If an API request returns an error (unable to fulfill order, rate limited, etc), the client will silently return the error payload without erroring out, which makes for an odd exception handling. Is this by design? Sorry if this issue is a duplicate

**Comment by rmm5t** [comment]
Could you please give a more concrete example? Which exact endpoint? Are you using the callback or promise signature? Are you using the latest version in the `master` branch?  See #148?

```
npm install coinbase/gdax-node
```

**Comment by itajaja** [comment]
promise signature. I am using `gdax@github:coinbase/gdax-node` version `0.5.0`. A couple of examples:

```js
await client.getProductTicker(productId)
// returns {'message': 'Rate Limit exceeded'} instead of erroring out
```

```js
await client.placeOrder(...)
// returns {'message': 'Not enough funds'} instead of erroring out
```

**Comment by rmm5t** [comment]
Thanks. I can confirm. This sounds like a definite bug. Investigating now.

```js
const params = {
  product_id: 'BTC-USD',
  type: 'limit',
  side: 'buy',
  price: '1000.00',
  size: '1000.00'
};

client.placeOrder(params)
  .then((data) => console.log('SUCCESS:', data))
  .catch((error) => console.log('ERROR:', error));

// SUCCESS: { message: 'Order size is too large. Maximum size is 250' }

client.placeOrder(params, (err, response, data) => {
  console.log('err:', err);
  console.log('statusCode:', response.statusCode);
  console.log('data:', data);
})

// err: null
// statusCode: 400
// data: { message: 'Order size is too large. Maximum size is 250' }
```

**Comment by itajaja** [comment]
I can work on a PR 🙌

**Comment by rmm5t** [comment]
I'm working on the test suite now. It doesn't look like there were any good negative tests (testing for error conditions). Well, there was one, but it was flawed.

**Comment by itajaja** [comment]
feel free to expand on my pr, or start from scratch 😊

**Comment by rmm5t** [comment]
Thanks. I'll take your PR (to give you credit), but I'll need to expand on it, because we need much better automated test coverage for these error conditions.

**Comment by itajaja** [comment]
makes sense, I would add the tests myself if I had more time 🙃

**Comment by rmm5t** [comment]
Thanks again @itajaja. See #210.

**Comment by aurbina83** [comment]
TDD TDD It'll save your life!
