### ISSUE TITLE
API on Sandbox Does not return BEFORE AND AFTER cursors

### ISSUE THREAD

**Issue by igostavro** [coinbase/gdax-node#214]
Requests I make to the list orders endpoint does not return before and after cursors. When I attempt to specify either the 'after' or 'before' query param I receive a:

"after cursor value is not valid" (and the corresponding 'before' error)

Any advice?

**Comment by rmm5t** [comment]
@igostavro Personally, I haven't found the sandbox to be a very reliable endpoint for testing, so you're not alone there. 

Regarding your report here, which specific endpoint are you trying to access on the sandbox that's causing you trouble?  Perhaps I can try to reproduce the same issue.

**Comment by igostavro** [comment]
Hey there! Thanks for responding.

ok so it looks like on SANDBOX that the headers sent back that contain the before and after cursor differ from the documentation in two ways:

1. They are lower case: cb-before and cb-after NOT CB-BEFORE and CB-AFTER
2. They are date time strings rather than integers.

Are these difference also present on the production environment?

**Comment by rmm5t** [comment]
> They are lower case: cb-before and cb-after NOT CB-BEFORE and CB-AFTER

That's the `request` library doing that. Yes, expect them to be lowercase in either environment.

> They are date time strings rather than integers.

I think it depends on which endpoint you're trying to use. You really shouldn't care what the type or meaning of the string is. Just use it as-is for a particular API endpoint

**Comment by igostavro** [comment]
Ah right, the issue was I was writing a test where I manually plugged in values similar to those found in the documentation and nothing I tried worked, it wasn't until I found the lower case 'cb' headers that I realized it expected those date time strings.

Anyways, thanks for your help :)

**Comment by rmm5t** [comment]
Cool. Please close this issue.
