### ISSUE TITLE
`message` errors not passed to the `error` handler

### ISSUE THREAD

**Issue by Bomper** [coinbase/gdax-node#219]
Probably related to #208. For example, subscribing with an invalid product_id returns an error to the raw on('message') socket, but not to the library.

```js
const gdax = require('gdax');
const websocket = new gdax.WebsocketClient(['ETH-GBP']);

websocket.on('message', data => { console.log(data.product_id, data.price); });  // undefined undefined
websocket.on('error', err => { console.error(err); });  // not reached
websocket.on('close', () => { console.error('close'); });
```

That sort of error (invalid product_id) is an application level one, which is why I guess it's returned in the `message` payload. However, to the user, this error is as critical as a websocket-level connectivity error, and handling it in `error` would be easiest.

**Comment by rmm5t** [comment]
This is not related to #208, but you still bring up an interesting point. 

> That sort of error (invalid product_id) is an application level one, which is why I guess it's returned in the message payload. 

Exactly.

> However, to the user, this error is as critical as a websocket-level connectivity error, and handling it in error would be easiest.

Agreed. Even though, this isn't a network-level error, the purpose of the WebsocketClient API is to provide a nice, normalized interface for different messages.

**Comment by rmm5t** [comment]
@Bomper See PR #221
