### ISSUE TITLE
Documentation Tool Used?

### ISSUE THREAD

**Issue by HanniAbu** [coinbase/gdax-node#220]
Hi, what tool do you use to build your documentation for https://docs.gdax.com/? I love it and would love to use it for a project I'm working with. If this is a custom solution, can this be made public in a separate repo?

**Comment by rmm5t** [comment]
You'll have to wait from someone from the GDAX team to chime in to get an accurate answer, but in the meantime, one of my favorites is slate (inspired by Stripe API docs):

https://github.com/lord/slate

**Comment by a--hoang** [comment]
Sorry for the delay in reply, we've been busy :) @rmm5t has the right idea - our docs were originally a fork off of slate, with some custom styles.

**Comment by a--hoang** [comment]
Closing as we've got the right solution here. Have a good day!
