### ISSUE TITLE
APIs on AuthenticatedClient gives error "Request timestamp is expired"

### ISSUE THREAD

**Issue by Sunillabs108** [coinbase/gdax-node#222]
Hi,
I am using nodejs client lib with sandbox URI.
I am getting following error always
const authedClient = new Gdax.AuthenticatedClient(key, secret1, passphrase, sandboxURI);
authedClient.getAccounts(callback)
Response:
"body: '{"message":"request timestamp expired"}'
Is there any way to fix this issue?

Please help.

Thanks and Regards

**Comment by rmm5t** [comment]
> `"body: '{"message":"request timestamp expired"}'`

Is your client machine's clock correct?

**Comment by Sunillabs108** [comment]
Thanks for  your suggestion, Yes it was machine's clock error.
It is working fine now
