### ISSUE TITLE
WebsocketClient interface connect/disconnect

### ISSUE THREAD

**Issue by brunoscopelliti** [coinbase/gdax-node#225]
Imho it would be useful to have websocket client's methods `connect` and `disconnect` exposed on the WebsocketClient interface.
What do you think?

**Comment by rmm5t** [comment]
**They are already exposed.**

Are you talking about the TypeScript definitions? \<rant\>_If so, stop holding yourself back with that terrible language._\</rant\> Feel free to submit a PR.

**Comment by brunoscopelliti** [comment]
Yes, sorry... I wasn't clear enough. The issue is related to typescript definition.
I'll submit a PR in the next days.
