### ISSUE TITLE
Heartbeat sequence numbers aren't sequenced

### ISSUE THREAD

**Issue by fenreer** [coinbase/gdax-node#227]
I've written a mix-in class for the node GDAX websocket client that ensures a stable connection with regular heartbeat sequencing and sane heartbeat replies over time. My irregularHeartbeat events are firing constantly and, when I print out the heartbeat sequence id directly from the message data, I get sequence numbers that make no sense at all:

2023518636
2023518825
2023518968
2023519080
2023519189
2023519243
2023519362
2023519455
2023519554
2023519737
2023519818
2023519948
2023520057
2023520229
2023520344
2023520426
2023520557
2023520679
2023520818
2023520897
2023520990
2023521076
2023521162
2023521279
2023521391
2023521473
2023521604
2023521729
2023521845
2023521947
2023521995
2023522160
2023522309
2023522430
...

Is anyone else experiencing this?

**Comment by rmm5t** [comment]
The sequence numbers in the heartbeat messages are not supposed to be sequential. Heartbeats only arrive once per second per product, and they just hold the current sequence number for that particular product.

The only way to get truly sequential sequence numbers is to subscribe to the `full` channel. 

More detail here:
https://docs.gdax.com/#sequence-numbers

> Sequence numbers are increasing integer values for each product with every new message being exactly 1 sequence number than the one before it.

The `heartbeat` channel serves two purposes.

1. It helps keeps the socket connection open.
2. It allows you to make sure that the connection hasn't gone stale from the server. i.e. If you don't receive a heartbeat message after several seconds, something is likely wrong and a reconnect is likely necessary.

**Comment by fenreer** [comment]
I understand now. The heartbeat sequence is as snapshot of that particular product's sequence number at the time the heartbeat message is sent. In the docs it read that the  sequence numbers should be sequential, but I misunderstood that this sequencing is only for the full channel (i.e. every message for that product).
