### ISSUE TITLE
inconsistency in readme

### ISSUE THREAD

**Issue by codeninja** [coinbase/gdax-node#228]
the readme documentation for getProductHistoricRates()  states 

publicClient.getProductHistoricRates('BTC-USD', { granularity: 3000 }, callback);

However the official documentation states 

"The granularity field must be one of the following values: {60, 300, 900, 3600, 21600, 86400}. Otherwise, your request will be rejected."

This should be changed in the readme and the last 25 minutes of my life refunded :)

**Comment by rmm5t** [comment]
Dupe of #205.
