### ISSUE TITLE
OrderbookSync throws error in a callback

### ISSUE THREAD

**Issue by petercerno** [coinbase/gdax-node#23]
`OrderbookSync` throws an error inside the callback `cb`, see e.g. the line:
```
throw 'Failed to load orderbook: ' + err;
```
in `lib/orderbook_sync.js`. This error is thrown, for instance, when there is no internet connection.
It is not easy to catch this kind of error in a client application. One option how to fix this problem would be to emit the error (instead of throwing it), e.g.:
```
self.emit('error', 'Failed to load orderbook: ' + err);
return;
```

**Comment by loriopatrick** [comment]
That's a good point. Do you want to make a PR? This is something I'd like to see.
