### ISSUE TITLE
Types inconsistencies

### ISSUE THREAD

**Issue by brunoscopelliti** [coinbase/gdax-node#231]
At the moment *.d.ts has some inconsistencies.
I am happy to contribute to improve it.

Another example, that is causing trouble to me, and possibly others:

```
getFills(pageArgs: PageArgs, callback: callback<any>): void;
getFills(pageArgs: PageArgs): Promise<any>; 
```

According to [docs](https://docs.gdax.com/#list-fills) I can pass an object with a `product_id` property to `getFills` to get the fills of a particular product (eg. BTC-EUR)...
It works at runtime, but it fails to pass typescript build. 

There's the same problem on [getOrders](https://docs.gdax.com/#list-orders), too.

Or again, the definition of `Account`:

```
  export type Account = {
      id: string,
      profile_id: string,
      currency: CurrencyType,
      balance: number,
      available: number,
      hold: number
  };
```
`balance`, `available` and `hold` are strings.

**Comment by fb55** [comment]
Yup, the interface wasn’t updated to allow this

**Comment by brunoscopelliti** [comment]
If you are ok, I can submit another PR in the next days...

**Comment by fb55** [comment]
@brunoscopelliti That would be dope

**Comment by brunoscopelliti** [comment]
@fb55 do you know when a new version will be published on npm?
