### ISSUE TITLE
Error Handling when Auth Data undefined

### ISSUE THREAD

**Issue by eperry** [coinbase/gdax-node#232]
I ran in to some errors when first writing my code, and I think the AuthClient needs handle Authentication a little better.

When one of the varibles are "undefined" the gdax api response with a Buffer error 
So for example this code ( authClient object printed out for visibility)

> var Gdax = require('gdax');
> var gdaxconfig = require('./gdax.config')
> const key = gdaxconfig.key;
> const secret = gdaxconfig.secret;
> const passphrase = gdaxconfig.passphrase;
> 
> const liveapiURI = 'https://api.gdax.com';
> const sandboxURI = 'https://api-public.sandbox.gdax.com';
> var apiURI=sandboxURI;
> const authedClient = new Gdax.AuthenticatedClient(key, secret, passphrase, apiURI);
> console.log(authedClient);
> authedClient.getAccounts((error,response,data)=>{
> });

As you can see in this example the b64secret is undefined

> AuthenticatedClient {
>   productID: 'BTC-USD',
>   apiURI: 'https://api-public.sandbox.gdax.com',
>   key: 'XXXXXXXXXXXXXXXXXXXXX',
>   b64secret: undefined,
>   passphrase: 'YYYYYYY' }
> 

It produces this Exception

> buffer.js:183
>     throw new TypeError(kFromErrorMsg);
>     ^
> 
> TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
>     at Function.Buffer.from (buffer.js:183:11)
>     at Buffer (buffer.js:158:17)
>     at module.exports.signRequest (/home/eperry/gdax/swinbot/node_modules/gdax/lib/request_signer.js:24:17)
>     at AuthenticatedClient.prototype._getSignature (/home/eperry/gdax/swinbot/node_modules/gdax/lib/clients/authenticated.js:60:15)
>     at AuthenticatedClient.prototype.request (/home/eperry/gdax/swinbot/node_modules/gdax/lib/clients/authenticated.js:50:32)
>     at apply (/home/eperry/gdax/swinbot/node_modules/lodash._createwrapper/index.js:72:25)
>     at AuthenticatedClient.wrapper [as get] (/home/eperry/gdax/swinbot/node_modules/lodash._createwrapper/index.js:415:12)
>     at AuthenticatedClient.prototype.getAccounts (/home/eperry/gdax/swinbot/node_modules/gdax/lib/clients/authenticated.js:78:26)
>     at Object.<anonymous> (/home/eperry/gdax/swinbot/test-auth.js:15:14)
>     at Module._compile (module.js:635:30)
> 

This is a very confusing exception, where I think the values of key, secret and passphrase should be tested at minimum to be something other then undefined. Maybe something like

>if ( key === undefined && typeof key === "string" ){
>    // Do some error message
>}

**Comment by rmm5t** [comment]
Just to distill this down a bit, are you simply asking for a better guard clause and improved error message when you pass invalid arguments to the `AuthenticatedClient`?

**Comment by rmm5t** [comment]
@eperry Please review #237
