### ISSUE TITLE
OrderbookSync throws errors - Response could not be parsed as JSON

### ISSUE THREAD

**Issue by axeldomingues** [coinbase/gdax-node#233]
I just executed the code below and got some errors listed below the code. Any ideas on what's wrong?

> const Gdax = require('gdax');
> const orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
> setTimeout(
>     function() { 
>         console.log("Los"); 
>     }, 30000);
> 
> setTimeout(
>     function() { 
>         console.log("Los"); 
>     }, 60000);
> 
> setTimeout(
>     function() { 
>         console.log("Los"); 
>     }, 90000);

(node:4472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to load orderbook: Response could not be parsed as JSON
(node:4472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Failed to load orderbook: Response could not be parsed as JSON

**Comment by rmm5t** [comment]
What version of the `gdax` library are you running? I cannot reproduce.

Are you sure you're using the latest?

**Comment by axeldomingues** [comment]
Hi,

I just npm install coinbase/gdax-node today. So I think it is the latest
version. Right?

Cheers
