### ISSUE TITLE
GDAX - request timestamp expired

### ISSUE THREAD

**Issue by PalvaiArjun** [coinbase/gdax-node#242]
Hi Guys,
I am seeing this issue "{"message":"request timestamp expired"}" with any/all private methods calls, where as public methods are returning status 200.
Below are examples of Public and Private method calls I made.

Public: working fine
authedClient.getProductTicker('ETH-USD',
(error, response, data) => {
if (error) {
// handle the error
} else {
var i = 0
var jsonString = JSON.stringify(response)
fs.writeFile("response.json", jsonString, 'utf-8', function(err) {
if (err) {
return console.log(err);
}
})
}
});

Private : Failed with time-stamp expired
authedClient.getFills(
(error, response, data) => {
if (error) {
// handle the error
} else {
var jsonString = JSON.stringify(data)
fs.writeFile("getFills.json", jsonString, 'utf-8', function(err) {
if (err) {
return console.log(err);
}
})
}
});

request_signer.js
const timestamp = Date.now() / 1000; // 1516414164.510 => Sun Jan 18 1970 13:13:34 (UTC)

I tried the code with "const timestamp = Date.now()", though this returns present time(Sat Jan 20 2018 02:09:24 (UTC)) I see no success.

The timezone is (UTC -05:00). The time will sync every 720 seconds. My system time is in sync with https://time.is/

Below is the error message for your reference.
{ statusCode: 400,
  body: '{"message":"request timestamp expired"}',
  headers: 
   { date: 'Sat, 20 Jan 2018 04:25:16 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '39',
     connection: 'close',
     'set-cookie': 
      [ '__cfduid=****; expires=Sun, 20-Jan-19 04:25:16 GMT; path=/; domain=.gdax.com; HttpOnly' ],
     'access-control-allow-headers': 'Content-Type, Accept, cb-session, cb-fp',
     'access-control-allow-methods': 'GET,POST,DELETE,PUT',
     'access-control-allow-origin': '*',
     'access-control-expose-headers': 'cb-before, cb-after',
     'access-control-max-age': '7200',
     etag: 'W/"27-****"',
     'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
     'x-content-type-options': 'nosniff',
     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
     server: 'cloudflare',
     'cf-ray': '3dff44d3bef49f4e-IAD' },
  request: 
   { uri: 
      { protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'api.gdax.com',
        port: 443,
        hostname: 'api.gdax.com',
        hash: null,
        search: null,
        query: null,
        pathname: '/accounts/7d0f7d8e-dd34-4d9c-a846-06f431c381ba/ledger',
        path: '/accounts/7d0f7d8e-dd34-4d9c-a846-06f431c381ba/ledger',
        href: 'https://api.gdax.com/accounts/7d0f7d8e-dd34-4d9c-a846-06f431c381ba/ledger' },
     method: 'GET',
     headers: 
      { 'User-Agent': 'gdax-node-client',
        Accept: 'application/json',
        'Content-Type': 'application/json',
        'CB-ACCESS-KEY': '******',
        'CB-ACCESS-SIGN': '*******',
        'CB-ACCESS-TIMESTAMP': 1516422316295,
        'CB-ACCESS-PASSPHRASE': '******' } } }

Any help is much appreciated.

Thanks

**Comment by prabhakar97** [comment]
I also faced the same problem. I have created a pull request to mitigate the issue. https://github.com/coinbase/gdax-node/pull/243

**Comment by fb55** [comment]
Please fix your local clock.

**Comment by PalvaiArjun** [comment]
Hi Guys,

I have my local time in sync with https://www.time.gov/ . I still see the same issue.
My CB-ACCESS-TIMESTAMP after conversion and expires time are same. 
Prabhakar, I tried with your code as well. It did not work. 
const timestamp = Date.now() + (options.clockSkew ? options.clockSkew : 0);

**Comment by prabhakar97** [comment]
@PalvaiArjun You need to make changes in two files, not just in request_signer. Here's the exact diff https://github.com/coinbase/gdax-node/pull/243/files

Or, the simpler way would be to update the dependency in package.json like so `"gdax": "prabhakar97/gdax-node"`
