### ISSUE TITLE
getProductTrades returns undefined

### ISSUE THREAD

**Issue by radiantone** [coinbase/gdax-node#244]
Hi,
   Looks as though this is not returning results. 

const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();
publicClient.getProductTrades('BTC-USD', function(trades) {
   console.log(trades);
});

**Comment by rmm5t** [comment]
You're using the callback signature. Like every callback in node, the first argument is _always_ the error. The current GDAX callback signature passes **3 arguments** to the callback function (`err`, `response`, and `data`).  You're assuming only `data` is passed.

Your code should instead read:
```js
publicClient.getProductTrades('BTC-USD', function(err, response, trades) {
  console.log(trades);
});
```

Alternatively, use the `Promise` signature:

```js
publicClient.getProductTrades('BTC-USD').then(console.log);
```

For more information read: 

* https://github.com/coinbase/gdax-node#using-callbacks
* https://github.com/coinbase/gdax-node#using-promises

---

**Please close this issue.**

**Comment by radiantone** [comment]
I appreciate that clarification. Thank you.
