### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by wannesdemaeght** [coinbase/gdax-node#246]
Websocket working good for a random amount of time (3 hours, sometimes only 5 minutes)
Then my script crashes with this error code:

```
url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at WebSocket.initAsClient (C:\Trader\Logic\node_modules\gdax\node_modules\ws\lib\websocket.js:525:25)
    at new WebSocket (C:\Trader\Logic\node_modules\gdax\node_modules\ws\lib\websocket.js:71:20)
    at Timeout.connect [as _onTimeout] (C:\Trader\Logic\node_modules\gdax\lib\clients\websocket.js:35:19)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Only started since I've upgraded to 0.5.1.

**Comment by rmm5t** [comment]
This is going to need more information about your environment.

* What version of the Node runtime are you running under?
* What version of the `ws` package are you locked to?
* What's the code look like that you use to instantiate the `WebsocketClient`?
* etc.

https://github.com/coinbase/gdax-node/blob/master/CONTRIBUTING.md#bug-reports

**Comment by wannesdemaeght** [comment]
Code:
```
    Gdax_Websocket = new GdaxLib.WebsocketClient(Market.Gdax.slice(1),"wss://ws-feed.gdax.com",null, {channels : [{"name" : "ticker"}]});
		Gdax_Websocket.on("message", data => {
			if (data.type == "ticker") {
				for (let coin = start; coin < end; coin++) {
					if (data.product_id == Market.Gdax[coin]) {
						Price.Bid.Gdax[coin] 	= Number(data.best_bid);
						Price.Ask.Gdax[coin]	= Number(data.best_ask);
					};
				};
			};
			if (data.type == "heartbeat") {
				for (let coin = start; coin < end; coin++) {
					if (data.product_id == Market.Gdax[coin]) {
						Ticker.New.Gdax[coin]	= data.sequence;
					};
				};
			};
		});
		Gdax_Websocket.on("open", data => {
			console.log("Websocket Gdax:        connected");
		});
```
ws version is 4.0.0
node version is 8.9.3

**Comment by wannesdemaeght** [comment]
when there hasn't been a heartbeat in 1 minute, I run this code to reinitiate connection:

```
try {Gdax_Websocket.disconnect()} catch(err) {};
setTimeout(Gdax_Websocket.connect, 1000);
```

**Comment by rmm5t** [comment]
> Only started since I've upgraded to 0.5.1.
> ws version is 4.0.0

It's not possible for you to be using _ws v4.0.0_ and _gdax v0.5.1_.

Did you actually mean that you're using the `master` branch of `gdax`?  Afterall, that's the only version that allows for _ws v4_.

> when there hasn't been a heartbeat in 1 minute, I run this code to reinitiate connection:

#226 and #229 might be relevant to this discussion.

**Comment by wannesdemaeght** [comment]
output of npm view ws version: 4.0.0
output of npm view gdax version: 0.5.1

**Comment by wannesdemaeght** [comment]
Did a manual reinstall to be sure:
```
C:\Trader\Logic>npm install coinbase/gdax-node
npm WARN logic@1.0.0 No description
npm WARN logic@1.0.0 No repository field.

+ gdax@0.5.1
removed 40 packages and updated 5 packages in 5.712s

C:\Trader\Logic>npm outdated
Package  Current  Wanted  Latest  Location
gdax       0.5.1     git     git  logic

C:\Trader\Logic>npm view gdax version
0.5.1

C:\Trader\Logic>npm view ws version
4.0.0
```

**Comment by rmm5t** [comment]
> `npm install coinbase/gdax-node`

Exactly. That means you're using the `master` branch, not the versioned release.

> `npm view gdax version`

[`npm view`](https://docs.npmjs.com/cli/view) does not show the currently installed version. It shows the latest version published to npmjs.com (same with (and [`yarn info`](https://yarnpkg.com/lang/en/docs/cli/info/)). 

Try [`npm ls`](https://docs.npmjs.com/cli/ls) or [`yarn list`](https://yarnpkg.com/lang/en/docs/cli/list/) instead (but that is still misleading if you're installing from a git repository)

To use the actual v0.5.1 release, you must perform `npm install gdax`.

----

Now, with all that said, the `master` branch should still be stable. My initial guess is that you're having a timing issue while you disconnect and try to reconnect the websocket. Are you noticing your underlying problem only when the heartbeat goes stale and you attempt one of your reconnects?

**Comment by wannesdemaeght** [comment]
I have no idea exactly what triggers the error, the reconnect is automatically induced when heartbeat goes stale. It completely crashes my node, so unable to see what happened before.

Switched over to this release now (was under the impression I was on it, but apparently wrong).
WS is now listed as 3.0.0

Hopefully it will be better now :-)

**Comment by fb55** [comment]
@wannesdemaeght Pretty simple JS error on your side. This line is the culprit:

```js
setTimeout(Gdax_Websocket.connect, 1000);
```

`connect` doesn't have a `this` binding here, which means it'll default to the global scope. The global scope doesn't have a `websocketURI` property, which fails in the websocket constructor.

**Comment by wannesdemaeght** [comment]
You're right, it needs to be:

> setTimeout(Gdax_Websocket.connect(), 1000);

Don't know how I missed that. Thanks!

**Comment by fb55** [comment]
It needs to be

```js
setTimeout(() => Gdax_Websocket.connect(), 1000);
```
