### ISSUE TITLE
Improve Build Matrix

### ISSUE THREAD

**Issue by rmm5t** [coinbase/gdax-node#249]
I'm extracting this from my comment on https://github.com/coinbase/gdax-node/issues/56#issuecomment-360166288

At a minimum, I'd like to see the build matrix run the test suite against:

* Existing LTS version of node (currently v6 _"Boron"_)
* Newer LTS version of node (currently v8 _"Carbon"_)
* Latest _unstable_ development version of node (currently v9), but potentially allowing the build to fail on this version without holding anything up.

There's also a potential for testing against different permutations of our dependencies, but that's less of an issue for general node package management and it only really has benefits if you're also using a tool like `yarn`.

I'd also like to see the testing tasks improved a little. I know we use `lint-staged` (I'm not a fan, btw, [because it breaks advanced git workflows](https://github.com/okonet/lint-staged/issues/62) ... that's a separate topic), but the test suite should also perform a sanity run of `eslint` and `prettier` to double check that pull-requests weren't submitted with the person's precommit hooks disabled. 

For example, the CI tests should look something like:

```
npm run eslint
npm run prettier
npm test
```

----

> While possible with parallel jobs, Circle isn't the best tool for this. Circle is good tool for private projects and applications, but Travis is far better tool for build matrices and libraries -- especially for open source projects.

@fb55 Thoughts here?

**Comment by fb55** [comment]
I'm using Travis for a bunch of private projects & really like it — happy to make the switch. The individual steps could also run in parallel (& with `sudo: false`) to speed up CI.

We should also specify version tags (like  [cheerio does](https://github.com/cheeriojs/cheerio/blob/25a51d7cb2edac34eb28cd51c89ca7a181ba0041/.travis.yml#L2-L5)) so the node version doesn't need to be bumped by hand. Just `6`, `stable` and `unstable` should give us enough coverage here.

**Comment by rmm5t** [comment]
>  Just `6`, `stable` and `unstable` should give us enough coverage here.

🤔 I don't think `stable` and `unstable` do what you think it does. Here's the output directly from Travis-CI:

```bash
$ nvm install unstable
$ node --version
v0.11.16

$ nvm install stable
$ node --version
v9.4.0
```

**Comment by fb55** [comment]
Okay, both of them are deprecated. Just [having `node`](https://github.com/creationix/nvm#usage) in there should make sure we always test on the latest version, which is what this was aiming at.

**Comment by rmm5t** [comment]
We’re going to implement this using a build matrix in CircleCI instead of Travis-CI.
