### ISSUE TITLE
Canceling all orders does not cancel stop order

### ISSUE THREAD

**Issue by petercerno** [coinbase/gdax-node#25]
When I call `cancelOrders` (or `cancelAllOrders`) from an `AuthenticatedClient`, it returns `0` cancelled orders even though I have one active buy-stop order on the `BTC-EUR` product.
Calling `cancelOrder` with the correct `orderID` works fine, although from time-to-time also this method fails with the `status code: 400`.

**Comment by loriopatrick** [comment]
Unfortunately named, `cancelAllOrders` only cancels all `open` orders. Stop orders after placed are in an `active` state. It may be worth it to rename `cancelAllOrders` to `cancelOpenOrders`. @mihar thoughts?

**Comment by JThobbyist** [comment]
I am experiencing this problem too

**Comment by aamazie** [comment]
I've been waiting for an extraordinarily long time to figure out how to do this. Does anyone have any idea?

**Comment by JThobbyist** [comment]
If stop orders are listed when you call getOrders() then you could getOrders after you cancelAllOrders and whatever is left cancel by iterating through with cancelOrder

**Comment by aamazie** [comment]
When I request get orders, I just get a [200] confirmation response, which I assume means there aren't any "open" orders but that the call went through.

**Comment by JThobbyist** [comment]
You’re getting that response code in the body?

**Comment by JThobbyist** [comment]
![e26de575-3db8-4ee7-b88b-982f10eef86e](https://user-images.githubusercontent.com/35932269/38964468-0098cee4-4345-11e8-8908-f3b02abc7ff8.png)

**Comment by JThobbyist** [comment]
(I use fibers and futures to make my code run synchronously when I need it to)

**Comment by JThobbyist** [comment]
Yeah this is a forum for “gdax-node”, as in nodeJS. You can definitely interconvert between JavaScript and python, js is easy to pick up, and if you run your command in js you can write your JSON.stringify-ed data to a text file and then read the file with python

**Comment by aamazie** [comment]
Ah. So it is. Well thanks @JThobbyist for showing me that at least it's possible :)

**Comment by rmm5t** [comment]
While I agree that this method is named somewhat unfortunately, the  API reference names it the same and also documents it as only canceling open orders. 
https://docs.gdax.com/#cancel-all

However, I did add some additional information to the README.
