### ISSUE TITLE
Error thrown from OrderbookSync receiving `change` with undefined price

### ISSUE THREAD

**Issue by krystophv** [coinbase/gdax-node#255]
Using master, it seem that under some condition, OrderbookSync will attempt to process a `change` message that contains no price (no idea why GDAX would be sending such a message):
```
\node_modules\bignumber.js\bignumber.js:1223
            throw error;
            ^

BigNumber Error: new BigNumber() not a number: undefined
    at raise (\node_modules\bignumber.js\bignumber.js:1191:25)
    at \node_modules\bignumber.js\bignumber.js:1179:33
    at new BigNumber \node_modules\bignumber.js\bignumber.js:194:67)
    at BigNumber \node_modules\bignumber.js\bignumber.js:164:24)
    at Orderbook.change \node_modules\gdax\lib\orderbook.js:116:19)
    at OrderbookSync.processMessage (\node_modules\gdax\lib\orderbook_sync.js:132:14)
    at emitOne (events.js:121:20)
    at OrderbookSync.emit (events.js:211:7)
    at OrderbookSync.onMessage (\node_modules\gdax\lib\clients\websocket.js:94:12)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage \node_modules\ws\lib\websocket.js:145:47)
    at Receiver.dataMessage (\node_modules\ws\lib\receiver.js:430:14)
    at Receiver.getData (\node_modules\ws\lib\receiver.js:368:12)
    at Receiver.startLoop (\node_modules\ws\lib\receiver.js:164:16)
    at Receiver.add (\node_modules\ws\lib\receiver.js:138:10)
    at TLSSocket._ultron.on (\node_modules\ws\lib\websocket.js:143:54)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
```
I haven't yet put in debugging code to try and catch the offending `change` message, but since BigNumber will actually throw an error, perhaps it would be good to wrap some of the calls to it and catch the error and emit an error event from the OrderbookSync instead of throwing the error up the stack. I've had this happen a few times in the past 24 hours, crashing out the application it was running within.

**Comment by lisbakke** [comment]
I've seen this, too. I'm not sure if it's intentional or not, but occasionally the websocket will emit a `change` event that has a `new_size` and an `old_size` but no `price`.

**Comment by krystophv** [comment]
It seems like, according to the API docs, that `change` events with `null` prices should be possible:

> Any change message where the price is null indicates that the change message is for a market order. Change messages for limit orders will always have a price specified.

But it's coming across as `undefined`, and the Orderbook code isn't prepared to handle that.

**Comment by lisbakke** [comment]
Have any gdax team members seen this?

**Comment by kyle-mccarthy** [comment]
It looks like it is also possible that an order doesn't contain a `size`, along with no `price` or `remaining_size`?

```
{ type: 'done',
  side: 'buy',
  order_id: '4802ecfe-b91d-4716-b175-2f33cbbcf759',
  reason: 'filled',
  product_id: 'ETH-USD',
  sequence: 2580402859,
  time: '2018-02-16T16:53:29.956000Z' }
```

**Comment by miwic** [comment]
Looks like there are some market orders that have change. Since the market order will not necessarily have price and size, there is potential for error. Not sure why the market orders have changes, since they should resolve immediately, but I have seen it in the full stream where a market order will be placed and at the same time stamp a change is received. Since the market orders do not have an "open" they will not be added to the order book, so the change should be ignored for the order id. The fix should be to check if order exists before converting price/size to BigNumber.
