### ISSUE TITLE
WebsocketClient: "IP does not match IP whitelist" when whitelist is specified STILL BROKEN

### ISSUE THREAD

**Issue by igostavro** [coinbase/gdax-node#257]
I am attempting to authenticate via the websocket:

initial message looks like:

$message = {array} [7]
 type = "subscribe"
 product_ids = {array} [1]
  0 = "ETH-USD"
 channels = {array} [1]
  0 = "user"
 signature = "REDACTED"
 key = "REDACTED"
 passphrase = "REDACTED"
 timestamp = 1517540226

and the first message back i get is:

 {array} [3]
 type = "error"
 message = "Sorry, you could not be authenticated: Unauthorized"
 reason = "IP does not match IP whitelist"

I know the values in the signature, key, passphrase and timestamp are correct because they work over the RestAPI.

Help needed! 

Please and Thank you.

**Comment by fb55** [comment]
Closing in favour of #201
