### ISSUE TITLE
getFills API returns data in unexpected format

### ISSUE THREAD

**Issue by adityamertia** [coinbase/gdax-node#259]
Hi, 
While calling getFills API with order_id param it returns data in unexpected format as below:

```
{
	"statusCode": 200,
	"body": "[{\"created_at\":\"2018-02-05T15:43:38.908Z\",\"trade_id\":3525742,\"product_id\":\"LTC-BTC\",\"order_id\":\"1b5cdf72-f829-4b0d-ae7b-b3bd2cf59052\",\"user_id\":\"59a96c25797a740156eec37d\",\"profile_id\":\"774234da-b2bb-4e88-9c9a-8dc7048835b8\",\"liquidity\":\"T\",\"price\":\"0.01812000\",\"size\":\"0.20000000\",\"fee\":\"0.0000108720000000\",\"side\":\"sell\",\"settled\":true,\"usd_volume\":\"26.8360000000000000\"}]",
	"headers": {
		"date": "Mon, 05 Feb 2018 15:43:40 GMT",
		"content-type": "application/json; charset=utf-8",
		"content-length"
```

Is order_id param not allowed as of now in getFills API or the API is broken ?
Fills response should be returned as below:
```
[
    {
        "trade_id": 74,
        "product_id": "BTC-USD",
        "price": "10.00",
        "size": "0.01",
        "order_id": "d50ec984-77a8-460a-b958-66f114b0de9b",
        "created_at": "2014-11-07T22:19:28.578544Z",
        "liquidity": "T",
        "fee": "0.00025",
        "settled": true,
        "side": "buy"
    }
]
```

**Comment by rmm5t** [comment]
Pasting results without pasting the code that got you there is a bit dubious.

However, it sounds like you're using the `callback` signature, but not using the [callback correctly](https://github.com/coinbase/gdax-node#using-callbacks) (similar to #244):  Your code should look like this:

```js
const order_id = 'd50ec984-77a8-460a-b958-66f114b0de9b';
client.getFills({ order_id }, (err, response, data) => console.log(data));
```

Or better yet, [start using promises](https://github.com/coinbase/gdax-node#using-promises):

```js
client.getFills({ order_id }).then(console.log);
```

----

Please close this issue if this resolves your problem.

**Comment by rmm5t** [comment]
Also relevant is this proposal/discussion: https://github.com/coinbase/gdax-node/pull/86#issuecomment-355633592

**Comment by adityamertia** [comment]
Thanks for clarifying.
