### ISSUE TITLE
websocket.unsubscribe is not a function

### ISSUE THREAD

**Issue by Thwar** [coinbase/gdax-node#262]
unsubscribe and subscribe events are not working for web sockets. I digged and found that the WebsocketClient class reads from index.d.ts which has this code below:

    export class WebsocketClient {
        constructor(
            productIds: string[],
            websocketURI?: string,
            auth?: {key:string, secret:string, passphrase:string},
            { channels }?: WebsocketClientOptions );

        on(event: 'message', eventHandler: (data:object) => void): void;
        on(event: 'error', eventHandler: (err:any) => void): void;
        on(event: 'open', eventHandler: () => void): void;
        on(event: 'close', eventHandler: () => void): void;
    }

Looks like it is missing the subscribe and unsubscribe event.  I am running this locally and using my API auth key too. Am I missing something?

Thanks!

**Comment by Thwar** [comment]
Thanks!

**Comment by fb55** [comment]
New version was published, npm works now.
