### ISSUE TITLE
module does not exist in the module map

### ISSUE THREAD

**Issue by ankitdesai** [coinbase/gdax-node#267]
hello, i'm trying to install this gdax library into a react-native application but having some trouble. after doing `npm install gdax` and including it in my js file (`import Gdax from 'gdax';`), i get the following error: 

```
Error: Unable to resolve module `stream` from
 `/PATH_TO_APP/node_modules/gdax/lib/clients/public.js`: Module does not exist in the module map
```

anyone else faced this issue? it seems like certain dependencies aren't being installed properly. any help is appreciated!

**Comment by fb55** [comment]
`stream` is a node-internal module that is not provided by react native. Try installing it from npm or provide some other variant of it.
