### ISSUE TITLE
TypeScript description for OrderResult#status is missing 'rejected' status

### ISSUE THREAD

**Issue by blair** [coinbase/gdax-node#269]
It is possible to post an order where the `status` is `'rejected'`, see the sample code in https://github.com/coinbase/gdax-tt/issues/149 .

The simple fix in gdax-tt:

  \-            if ((result as any).message) {
  \+            if (result.status === 'rejected' || (result as any).message) {

generates this error message:

`src/exchanges/gdax/GDAXExchangeAPI.ts(255,17): error TS2365: Operator '===' cannot be applied to types '"open" | "pending" | "received" | "done"' and '"rejected"'.`

So `gdax/index.d.ts` needs to be updated.

**Comment by fb55** [comment]
Fixed in #270
