### ISSUE TITLE
API returning same trades: not updating

### ISSUE THREAD

**Issue by radiantone** [coinbase/gdax-node#272]
This morning I am seeing the same trades from about 10 minutes ago coming through the API. They are not updating like they did before. Looks like it's stuck on the same trade data and not refreshing.

**Comment by radiantone** [comment]
Nevermind. I see it says rate limit exceeded. This must be new.

**Comment by fb55** [comment]
Please use the websocket API to retrieve live data. The REST API caches non-user-specific information for brief periods.
