### ISSUE TITLE
Error while accessing FIX interface

### ISSUE THREAD

**Issue by siberianguy** [coinbase/gdax-node#274]
I'm trying to access GDAX FIX endpoint without any luck. As this repository doesn't support FIX I tried [gdax-fix-client](https://github.com/Saurox/GDAX-Fix-Client) but I get `session ended` and `stream ended` messages right after connection (so logon doesn't happen).

I find it a little suspicious that the official gdax-node wrapper doesn't support FIX, so it makes me think may be FIX endpoint is not functioning well (I hardly see any evidence of people using it).

After several days of trying to make FIX work, I'm extremely frustrated and my only hope is that here're GDAX developers who could shed light on the whole FIX situation.

**Comment by fb55** [comment]
The REST API is what is currently recommended for most traders.
