### ISSUE TITLE
Re: Can't receive client_oid #141

### ISSUE THREAD

**Issue by franklin770** [coinbase/gdax-node#287]
I too am having the same issue as #141 

I create a guid in c# and pass it in an async call.

Guid client_oid = Guid.NewGuid();

The id that I receive in the response is not the same as the one I sent and I cannot identify the trade.
I am using the sandbox and am not using the websocket feed.

so,  
Is this a sandbox issue?
Is my guid invalid since it is GUID and technically not UUID?
Is it because I need to specifically use websockets to get the client_oid ( and what I am seeing is the gdax order_id?)

Any help would be appreciated

Thanks
bob

**Comment by fb55** [comment]
Client order IDs will only be broadcasted on the feed. From the [docs](https://docs.gdax.com/#client-order-id):

> The optional client_oid field must be a UUID generated by your trading application. This field value will be broadcast in the public feed for received messages. You can use this field to identify your orders in the public feed.
> 
> The client_oid is different than the server-assigned order id. If you are consuming the public feed and see a received message with your client_oid, you should record the server-assigned order_id as it will be used for future order status updates. The client_oid will NOT be used after the received message is sent.
