### ISSUE TITLE
client_oid not received on the order feedback message

### ISSUE THREAD

**Issue by seddikouiss** [coinbase/gdax-node#289]
Hello, I success sending a new order with a client_oid in the message, but in the feedback message received just after, the client_oid is not present. The documentation says that we need to request the public feed in order to retrieve the order with the client_oid of our previous order message. It is the only way to make match our order sent with the one on GDAX ? Is there a way we can receive the client_oid on the feedback message of our order ? thank you to answer.

**Comment by fb55** [comment]
It is — the message you get in response to your request will contain the actual order id, which is not user-supplied.
