### ISSUE TITLE
Delay on available Balances updated

### ISSUE THREAD

**Issue by sfkiwi** [coinbase/gdax-node#291]
I am finding that the /accounts api endpoint is intermittently incorrectly reporting the available balance after a trade has executed. I am listening for the `done` message via the websocket and once it has been received I am fetching the balance via the /accounts API.  Often but not always the available balance that comes back has not yet updated after the prior trade. 

This means that you essentially either need to just try again later or keep polling the accounts endpoint until the balances show up, neither of which are particularly elegant solutions. I would have expected that the balances would have been updated as part of finalizing the trade so perhaps the /accounts endpoint is possibly using cached data.

**Comment by fb55** [comment]
Settlement is done asynchroneously. It should be fairly quick, but never realtime. If you need to now the available balances immediately polling is your best option, just note that you might get rate-limited if you are too aggressive. If you can wait, try again after ~10s, often times balances should have been updated by then.
