### ISSUE TITLE
Erroneous Insufficient Funds messages due to gdax updating balances in clearing process

### ISSUE THREAD

**Issue by lisbakke** [coinbase/gdax-node#292]
Hello! I sent a message on issue #128 but I wasn't sure if notifications are sent to you guys on closed issues. Sorry ahead of time for filing a dupe!

There's still an issue where if you:
1) Have an open order
2) Cancel it -- and receive confirmation from GDAX that it is canceled (confirmation has been tested on FIX / REST / Websocket)
3) Immediately try to place a new order

You can occasionally get an error on step 3 saying that you have Insufficient Funds because the funds are still locked up from step 2.

I was just wondering if there's any update on this since it's been 5 months or so.

What's the recommend way to deal with this from our side? Continue to resubmit orders until they go through?

**Comment by fb55** [comment]
There is no recommended way. Resubmitting definitely works, as would operating on a subset of the available funds. Both are far from ideal, and we intend to fix this. As @davidcaseria said on the other issue:

> We have plans to address this issue which will transparently un-hold funds for FIX API users.
