### ISSUE TITLE
Request: Canary version

### ISSUE THREAD

**Issue by sfkiwi** [coinbase/gdax-node#297]
Would it be possible to have a canary release of the library any time a PR is merged into master? Similar to how chaijs does it? https://github.com/chaijs/chai/issues/751 

That way you can use the @canary tag to specify you want the bleeding edge build. For small changes this would speed up development instead of having to wait for the next official release.

**Comment by rmm5t** [comment]
Interesting concept, but to me, this doesn't sound like the best approach for a project like gdax-node. Also, it doesn't look like chai adopted their canary releases. i.e. They haven't had a canary release in over a year.

Instead, for "bleeding edge," I would recommend just referencing the master branch directly.

```bash
npm install coinbase/gdax-node
```

I'd also like to make it a plan for the future (if possible) that we publish releases more frequently here as well, so some of this becomes moot to some degree.
