### ISSUE TITLE
getOrders pagination failing

### ISSUE THREAD

**Issue by spillikins** [coinbase/gdax-node#305]
When adding before: or after: elements to the getOrders request it fails. 

For example on an open orderbook with over 100 orders the request https://api.gdax.com/orders?before=2&status=open&limit=10 is part of the error response and looks valid yet the response fails with { Error: HTTP 400 Error: before cursor value is not valid.

**Comment by fb55** [comment]
`before` has to be an order id

**Comment by Lubomirusa** [comment]
[https://github.com/coinbase/gdax-node/issues/326](url)
It should be `created_at` value.

**Comment by Nicholas-t** [comment]
does it have to also be processed somehow? because when i just put the created_at value it gives me an error invalid positive integer value
Thanks in advance
