### ISSUE TITLE
Get order detail in sandbox does not work

### ISSUE THREAD

**Issue by MukundSonaiya** [coinbase/gdax-node#313]
Hi, 

```
authenticatedClient.getOrder("a8c9ee80-6a6e-4ac2-9481-695326d33cc7",function callback(error, response, data){
    if (error) {
        console.log("Order Detail error",error);
    } else {
        console.log("Order Detail data",data);
    }
});
```

I am trying to get the detail of the above GDAX order id. I can see the details on the GDAX sandbox platform, but when I try to get detail using the api I am getiing below error : 
```
data: { message: 'NotFound' } }
```
This was working day before yesterday.

**Comment by fb55** [comment]
The sandbox has separate orders from the production deployment. You will have to specify the API endpoint for the sandbox to retrieve orders created there.
