### ISSUE TITLE
Feature request : depth of the orderbook

### ISSUE THREAD

**Issue by machard** [coinbase/gdax-node#315]
Hi,
Processing a full orderbook take some cpu power and is not useful when we only care about the first levels.
Do you plan to allow subscribers to level2 orderbook to pass a `depth` parameter ?
Thank you

**Comment by fb55** [comment]
There is no work being done to add a depth parameter, but we have talked about adding a level 1 channel before. Would that be what you want? In this case, you would always now the best bid and ask.

**Comment by machard** [comment]
@fb55 would be good yes!

**Comment by machard** [comment]
@fb55 any timeline ?

**Comment by machard** [comment]
@fb55  ?

**Comment by fb55** [comment]
The ticker channel already provides the best ask and bid, but groups matches. A proper level 1 channel could be provided at some point, but this should work for a lot of cases.

**Comment by machard** [comment]
yep but if price moves without a trade happening, ticker is not fired, am i right ? @fb55

**Comment by machard** [comment]
@fb55 problem with ticker channel is that it seems to be delayed and suffer big lags sometimes.
I see clearly the difference between level2 feeds and ticker.
I just monitor Date.now() - msg.time on my side to see this
<img width="1174" alt="capture d ecran 2018-08-14 a 11 27 02" src="https://user-images.githubusercontent.com/5071029/44071698-fec4493c-9fb4-11e8-8437-20e20f687790.png">
On the graph above I switched half of my stream (the USD ones) to ticker and you can clearly see the lags

**Comment by machard** [comment]
@fb55 actually, I just discovered the undocumented level2_50 channel that you use in the UI. Which is already a good improvement
