### ISSUE TITLE
Still usable for Coinbase Pro and Prime?

### ISSUE THREAD

**Issue by stephenhuh** [coinbase/gdax-node#327]
Hey there,

I was using this library to use gdax, but have seen that gdax has been moved (or rebranded) as **coinbase pro**. Would this lib still be maintained and usable for Coinbase Pro & Premium?

**Comment by fb55** [comment]
The library will continue to work for Coinbase Pro and Coinbase Prime. API tokens generated on both platforms are still usable with it and the library will be rebranded relatively soon.

**Comment by unicornsoftwareinc** [comment]
Hi there, is this still the case today? Are API tokens generated on Coinbase Prime usable with this API?
