### ISSUE TITLE
URLs in library still pointing to gdax and not coinbase

### ISSUE THREAD

**Issue by adityamertia** [coinbase/gdax-node#335]
Hello,

Is the library required to change the URLs for websocket and API from gdax.com to pro.coinbase.com? Or will it work seamlessly with gdax.com as well?

Thanks
Aditya

**Comment by fb55** [comment]
The GDAX API is still active. For now no action is required, the library is usable as-is.

**Comment by aricallen** [comment]
would you guys accept a PR with the README links/code updated to the new `docs.pro.coinbase` site/endpoints? Even if the old ones are still active, this would at least be a good step forward.

**Comment by vansergen** [comment]
It is fixed in the https://github.com/coinbase/gdax-node/pull/346

**Comment by fb55** [comment]
It is, thanks for flagging!
