### ISSUE TITLE
Get historical data

### ISSUE THREAD

**Issue by AdvaithD** [coinbase/gdax-node#336]
I'd like to get historical data for BTCUSD, ETHUSD etc

Whats the best way to get historical data(about 1y, 2yr) for the following pairs?

**Comment by vansergen** [comment]
There is a function for that. Check  [`getProductHistoricRates`](https://docs.pro.coinbase.com/#get-historic-rates). For example
```javascript
publicClient.getProductHistoricRates('BTC-USD', { 
  granularity: 3600,
  start : '2017-09-19T18:22:05.068932Z',
  end: '2017-10-01T12:47:25.253Z' }, callback);
```

**Comment by AdvaithD** [comment]
Thanks
