### ISSUE TITLE
Getting account balance via websocket

### ISSUE THREAD

**Issue by adityamertia** [coinbase/gdax-node#337]
Hi,

Is there a way to fetch account balance using websocket in gdax? If yes how?

Aditya

**Comment by fb55** [comment]
Right now there is no official way to do this.

**Comment by vansergen** [comment]
There is a way(to listen updates). You can check your balance with REST request and after that all balance updates you can get on `user` websocket channel. For example, you receive a message with type `open`, `match` or `canceled` then you update your balance according to the message.

**Comment by fb55** [comment]
The way @vansergen proposed is how the website implements this.

**Comment by MattMav** [comment]
I don't believe the User channel was available around the time this was originally posted. Would the User channel be a way to get account specific information?

I'm trying to accomplish the same thing and having issues with the Authentication. 

If you know or if you have any ideas please let me know. 

Thanks,
MM
