### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by machard** [coinbase/gdax-node#338]
Hi,

I was looking into a way to have different profiles to run multiple strategies using independent balances and I did create a new profile using a "POST /profiles" request. Now I can create API keys targeting this new profile. And these keys work as I have been able to deposit on one account of this new profile. So I guess now I can trade via the API with this new profile..

This is not documented, so I have to ask if I can safely use this feature ?
Only problem I noticed is that the coinbase pro UI is not really handling the multiple profiles. It seems to use the default one but it causes some little issues in some places.

Thank you

**Comment by fb55** [comment]
The website always uses the default profile. Profiles are a feature exclusive to API traders (for your exact use-case) and are a supported feature. I agree that we can do a better job documenting them though.

**Comment by vansergen** [comment]
Could you please specify the request?
I tried to reproduce this profile creation with `POST /profiles ` with `body: '{"profile_id":"new_test"}'` and with empty `body`. I got the following error: `Error: HTTP 403 Error: Forbidden`

**Comment by machard** [comment]
I had several tries.
By looking at my postman history I think this was the successful one
<img width="837" alt="capture d ecran 2018-10-02 a 11 13 57" src="https://user-images.githubusercontent.com/5071029/46328923-66cb5200-c634-11e8-8a66-3c448fe48384.png">
<img width="838" alt="capture d ecran 2018-10-02 a 11 13 18" src="https://user-images.githubusercontent.com/5071029/46328924-66cb5200-c634-11e8-8ee7-035bbb42f88b.png">

**Comment by fb55** [comment]
The profile id is the id of this specific profile, not its name. You can list all profiles using an authenticated `GET /profiles`.

**Comment by AntonioJuliano** [comment]
> The website always uses the default profile. Profiles are a feature exclusive to API traders (for your exact use-case) and are a supported feature. I agree that we can do a better job documenting them though.

Checking a year later, is this feature still supported?

Also is there any documentation about this at all? The only thing I was able to find was this issue, and a few instances of `profile_id` in return values in the API docs
