### ISSUE TITLE
Add withdrawPayment to index.d.ts

### ISSUE THREAD

**Issue by reenko** [coinbase/gdax-node#364]
API have public method `withdrawPayment`
https://github.com/coinbase/coinbase-pro-node/blob/master/lib/clients/authenticated.js#L286-L293

But on `index.d.ts` this method was skip.
https://github.com/coinbase/coinbase-pro-node/blob/master/index.d.ts#L308-L312

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
