### ISSUE TITLE
Charging?

### ISSUE THREAD

**Issue by Leteen** [coinbase/gdax-node#366]
Hi how can I charge an user?,

I'd like to bind a discord ID to a payment, so if the user pays 1 usd, the user gets 2 virtual coins, that I'll be doing later, but I need a method to create a commerce.coinbase/charges/<OrderID> link, thanks

**Comment by vansergen** [comment]
Did you check [this](https://github.com/coinbase/coinbase-commerce-node) library?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
