### ISSUE TITLE
Property 'getPaymentMethods' does not exist on type 'AuthenticatedClient'

### ISSUE THREAD

**Issue by theRealScoobaSteve** [coinbase/gdax-node#370]
issue: If your using typescript, getPaymentMethods does not exist on the authenticated client, yet should be.

Steps to reproduce:
Simply create a typescript node project, connect to an authenticated client and call the method. You will get an error at compile time because the method is not defined on the Authenticated Client.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
