### ISSUE TITLE
publicClient.getTicker not working in Safari

### ISSUE THREAD

**Issue by DA37708** [coinbase/gdax-node#373]
publicClient.getProductTicker('BTC-USD') errors in Safari with: Request header field User-Agent is not allowed by Access-Control-Allow-Headers in safari on iOS 12.3

Works fine in Chrome on Windows 10. Is there anything I can do to get this to work in the safari browser on my phone?

Thanks for the help

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
