### ISSUE TITLE
Feature Request: Add Webhook Notifications to Coinbase Pro

### ISSUE THREAD

**Issue by pmm1** [coinbase/gdax-node#379]
I noticed that a lot of functionality is not available in the Coinbase Pro API but is available via the basic Coinbase API.

Webhook Notifications and other important functionality don't seem to be available in Coinbase Pro API.

How do you get around this issue, do I need to transfer funds to the normal Coinbase account so that the Notifications will work?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
