### ISSUE TITLE
Does this library work with Coinbase Prime

### ISSUE THREAD

**Issue by unicornsoftwareinc** [coinbase/gdax-node#385]
Hi there, I have a customer who wants to hook up their Coinbase Prime account to my app. The only problem is I'm not sure that API keys generated on that platform will work with my app which uses this library.

According to this ticket from 1 year ago, https://github.com/coinbase/coinbase-pro-node/issues/327 , API keys made on both Coinbase Pro AND Coinbase Prime should work with this library. Is that still the case?

Thanks!

**Comment by vansergen** [comment]
@hugeprestigellc Yes, it works with Coinbase Prime. As @fb55 confirmed earlier:
> The library will continue to work for Coinbase Pro and Coinbase Prime. API tokens generated on both platforms are still usable with it

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
