### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by kevin192291** [coinbase/gdax-node#388]
I am getting an invalid signature error. Debugging though it seems that a signature is being created, so, I am not sure why I am getting this. Here is my code from the demo on this github page.

```
const key = 'and my key';
const secret = 'my correct sec';
const passphrase = 'and and my passph';

const sandboxURI = 'https://api-public.sandbox.pro.coinbase.com';

const authedClient = new CoinbasePro.AuthenticatedClient(
  key,
  secret,
  passphrase,
  sandboxURI,
);
authedClient.getOrders().then(orders => {
    console.log(orders);
}).catch(err => {
    console.log(err);
});

```
the error is:
`Error: HTTP 400 Error: invalid signature`

Am I doing something wrong or missing something here?
Thank you!

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
