### ISSUE TITLE
cancelOrders returning wrong data

### ISSUE THREAD

**Issue by davidmarcoes** [coinbase/gdax-node#389]
For the last 24/48 hours the `cancelOrder` method in the authenticated API has been returning wrong data:

- Expected: an array of one element containing the id of the cancelled order
- Actual: an array containing a non id value (like this `[ '2' ]`)

I'm on version 0.9.0 of the library and node 12.3.1.

**Comment by davidmarcoes** [comment]
So the actual problem is that instead of returning an array containing a single element (the cancelled order id) the function is now returning the id itself.

So given an order with id `123456ab-defg-...` and an expected value of `['123456ab-defg-...']`, any attempt of accessing the returned id (using `id[0]`) now results in the very first character of the id itself.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
