### ISSUE TITLE
withdrawCrypto funds getting stuck

### ISSUE THREAD

**Issue by gigamesh** [coinbase/gdax-node#390]
I'm trying to withdraw from my pro.coinbase.com ETH account but the funds end up just going to my coinbase.com account and I get an error that says: 

> The funds were transferred to Coinbase for processing, but failed to withdraw to <localAddress>. Please manually withdraw from Coinbase.

Is it not possible to transfer directly out?  What I'm doing wrong? 

```
  const params = {
      amount: 0.01,
      currency: "ETH",
      crypto_address: localAddress
    };

    client.withdrawCrypto(params, (error) => {
      if (error) {
        console.error(error);
      }
    });
```

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
