### ISSUE TITLE
[Q] Whats the difference between authedClient.placeOrder and authedClient.sell

### ISSUE THREAD

**Issue by matze19999** [coinbase/gdax-node#391]
Which one do I have to choose if I want to sell everything from a specific coin instantly?

Thanks!

**Comment by vansergen** [comment]
@matze19999 There is no difference.  You can do both (buy and sell) with the `placeOrder ` method. The `sell` method actually calls the `placeOrder` method:
https://github.com/coinbase/coinbase-pro-node/blob/8bce637716bf73669337398fe53df24b2d25af1b/lib/clients/authenticated.js#L118-L121

**Comment by matze19999** [comment]
Ahh, thank you! :)
