### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by nikulis** [coinbase/gdax-node#41]
Are there currently any plans to add promise support in the API clients? It would be very nice for those who like to write promise-style rather than use callbacks.

To use an example from the README, the following code:

```js
var callback = function(err, response, data) {
  // your code here.
};

authedClient.getOrders({'after': 3000}, callback);
```

…could instead be used as:

```js
authedClient.getOrders({'after': 3000})
  .then(result => {
    let { data, response } = result; // Still expose underlying response object?
    /* do stuff with data */
  })
  .catch(err => { /* handle error */ });
```

Furthermore, returning a promise would also allow for use with async/await, e.g.

```js
async function myFunction() {
  try {
    let { data, response } = await authedClient.getOrders({'after': 3000});
    /* do stuff with data */
  } catch (err) { /* handle error */ }
}
```

From an implementation perspective, I think it would be totally possible for the same functions to support callbacks and promises at the same time, without making any breaking changes. For example, existing functions could run callbacks as normal if provided and return a promise if no callback is provided. Or, as the current API call functions don't return anything, they could just always return a promise (but still execute a callback if provided).

I haven't been able to find any documentation about minimum versions of Node that this project must/wants to support, but with PR #40 starting to overhaul and ES6-ify things, I'm guessing that using native ES6 promises would be fine platform-support-wise.

I also haven't seen any contributing guidelines, but I'd be happy to pitch in and help implement this if it's something more people would like.

**Comment by awitherow** [comment]
This would be super ideal!
