### ISSUE TITLE
OrderBookSync does not emit "message" event

### ISSUE THREAD

**Issue by jonnyasmar** [coinbase/gdax-node#43]
Pretty simple one. The OrderBookSync overrides WebsocketFeed's `onMessage` method, but in-so-doing does not emit the `message` event as WebsocketFeed does.

**Comment by jonnyasmar** [comment]
Oops... didn't notice this had been fixed. Sorry! :)

**Comment by awitherow** [comment]
@jonnyasmar any specific ticket that fixed this?

**Comment by mjesuele** [comment]
#35 (just happened to be looking at it now)
