### ISSUE TITLE
Error: getaddrinfo ENOTFOUND api.gdax.com api.gdax.com:443

### ISSUE THREAD

**Issue by awitherow** [coinbase/gdax-node#44]
I am not sure which method is doing this, but the error handling functionality of gdax-node does not seem to be working much at all if these errors are not being passed to the err prop in the callback. They are slipping into the data prop and not working with the way I am using promises to resolve and reject all the functions this project has to offer.

**Comment by iTester321** [comment]
Has this issue been closed ? what was the solution ?
