### ISSUE TITLE
Authenticated getProductOrderBook overridden

### ISSUE THREAD

**Issue by pgray64** [coinbase/gdax-node#46]
Is there a particular reason why the authenticated getProductOrderBook is overridden as function(args, productId, callback)? The change of arguments from the public version getProductOrderBook = function(args, callback) is not documented anywhere but the source.

**Comment by nikulis** [comment]
I agree that the authenticated client should not override this.

A [blame](https://github.com/coinbase/gdax-node/blame/cdea38a18b0609aed97b877483444d5ea975cd32/lib/clients/authenticated.js#L163) reveals that the code was inserted with a comment describing it as a "temp override" in faece04 as part of coinbase/coinbase-exchange-node#35 (no description provided).

It was then used in [`bf6c2a4`](https://github.com/coinbase/gdax-node/commit/bf6c2a4503032ce76482aba389817040323c1fd2#diff-b8485adf65396e9a8815ffa587a1ce96R51) to add support for `OrderbookSync` to use an existing authenticated client as part of coinbase/coinbase-exchange-node#37 (no description provided).

I'm not sure as to the rationale of why these changes were introduced.

More recently, #37, which added support for multiple order books (specifically [2fd3464](https://github.com/coinbase/gdax-node/pull/37/commits/2fd3464a21da9a575f1a2656d36168cd9b04c4e0#diff-b8485adf65396e9a8815ffa587a1ce96R64)), seems to have taken a new approach by memoizing `PublicClient`s for each requested book type, which seems like a better way to go imho.

Tagging relevant committers who may have some more insight:
@cilphex, @maxim-s, @fb55
