### ISSUE TITLE
How to pass options/parameters to API methods

### ISSUE THREAD

**Issue by jhanstra** [coinbase/gdax-node#51]
This is possibly a dumb question but I don't understand how to pass options to the API methods. For example, in `publicClient.getProduct24HrStats((err, res, data) => { })`, where do I specify that I want the stats on Ethereum, not Bitcoin? Is this possible?

**Comment by awitherow** [comment]
Apparently when you initialise the publicClient, you can pass in a productID you want to use there

https://github.com/coinbase/gdax-node/blob/57afad7f7c401ccc6da36d273f14703f0c8a8ea0/lib/clients/public.js#L10

**Comment by jhanstra** [comment]
Ah, I see. I might submit a PR for better documentation on that. Thanks @awitherow!

**Comment by awitherow** [comment]
I already did @jhanstra https://github.com/coinbase/gdax-node/pull/52 does it make sense for you?
