### ISSUE TITLE
getProductTrades swallows errors

### ISSUE THREAD

**Issue by Miladinho** [coinbase/gdax-node#63]
You should implement the [callback pattern](https://blog.yld.io/2015/10/19/the-callback-pattern/#.WT3MVRPyuAx), it makes a developers life a lot easier and i would argue it is good practice to do in a crazy untyped language like javascript.

a callback should be of the form:
`function callback(error,result) {
}`

If my understanding is correct:
The first callback argument is null or undefined;
The second argument contains the callback results.
On the other hand, if an error occurred:
the first argument contains an error object, an instance of the JavaScript Error class (or sub-class) that describes the error;
the second argument will be undefined.

Your getProductTrades function at least, is returning null for the error parameter regardless of a success of failure. So what is even it's use and why is it mentioned as part of your specific callback?

**Comment by fb55** [comment]
Good point, we definitely shouldn't ignore errors here.

**Comment by Miladinho** [comment]
@fb55 
I see why you changed the title, on that note, you should implement callback pattern, makes everything easier. I have solutions for the current problems, i'd like to do a pull. I am a big advocate for TDD and plan to spend some time fixing and refactoring the whole project.

**Comment by fb55** [comment]
@Miladinho That's great! We already have a big refactoring going on in #60, but there can never be enough helping hands. Especially test coverage is always a big win, please let me know if there is anything I can do to help.

**Comment by Miladinho** [comment]
@fb55 
I added some test code and refactored stuff. The code is suppoused to fail because the test I wrote is addressing the problem referred to in this bug report. I wanted to draw attention to the problem to the rest of the developers before writing the code that would pass the test. Please see #68

**Comment by rmm5t** [comment]
I think this is safe to close out now.

**Comment by Miladinho** [comment]
@rmm5t 

I have been meaning to follow up on this, you can close it for now. I will study what changes have been made to see if what I was referencing is still an issue or not.

**Comment by rmm5t** [comment]
> you can close it for now

Only the original author or a repo contributor can close this out. I'm neither 😞
