### ISSUE TITLE
error of orderbookSync.books['ETH-USD'].state()

### ISSUE THREAD

**Issue by amazingandyyy** [coinbase/gdax-node#69]
when I followed [this](https://github.com/coinbase/gdax-node#orderbook-sync)
I got error messages as showing 
`TypeError: Cannot read property 'ETH-USD' of undefined`

**Comment by Thien42** [comment]
+1
orderbook seems to come back undefined when using
`var orderbook = new gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);`
I tried with various currencies and I got the same result

**Comment by amazingandyyy** [comment]
@Thien42 yes, since we install via npm, the version is 0.4.2, we can only use 
```javascript
var orderbook = new Gdax.OrderbookSync('ETH-USD'); // you can only use one product, in stead [];
```

**Comment by amazingandyyy** [comment]
I hope they can update to 0.4.3 as another issue I open #70

**Comment by Thien42** [comment]
@amazingandyyy Thanks for your answer !
I will use the github version for a while then !

**Comment by fb55** [comment]
I'm assuming this has been fixed.
