### ISSUE TITLE
needs to be upgraded to 0.4.3 on npm ASAP

### ISSUE THREAD

**Issue by amazingandyyy** [coinbase/gdax-node#70]
I have huge problem of using `OrderbookSync` when I follow the docs on github
After going back to check the source code, I saw a huge difference between the code on github and the one I installed via npm.

If the documentation is for version 0.4.3, then we should publish this version to npm

**Comment by ctubio** [comment]
yep, because https://github.com/coinbase/gdax-node/pull/67 is not yet at https://www.npmjs.com/package/gdax

**Comment by ctubio** [comment]
meanwhile, a nice temp fix at https://github.com/samuelhug/Krypto-trading-bot/commit/f92530b4e7207222c43af76a2ab93ac7ba3befe3

**Comment by amazingandyyy** [comment]
@ctubio good idea Thank you!

**Comment by michaelbpaulson** [comment]
Update?

**Comment by JensvdHeydt** [comment]
Any update ??

**Comment by jbrocker** [comment]
Hear hear!

**Comment by rmm5t** [comment]
@amazingandyyy  Would you mind closing this issue in favor of consolidating the discussion under #148? There's a wider discussion about frequent version releases going on there.

**Comment by amazingandyyy** [comment]
@rmm5t sure! thanks
