### ISSUE TITLE
lazy PR

### ISSUE THREAD

**Issue by ctubio** [coinbase/gdax-node#75]
feel free to cherry-pick https://github.com/ctubio/gdax-node/commit/2ae06d1337283286dceee203900e7bb4ef1d24f1 and https://github.com/ctubio/gdax-node/commit/08be19b86bae1aa5a19f1451cd43e8774c46f159, i didnt make a PR cos my fork is reverted to v4.2 because https://github.com/coinbase/gdax-node/issues/62 is still not fixed in your master branch (and im using my good working fork stucked at 4.2 for my app [and im lazy to multi-fork, so no PR, sorry])

**Comment by rmm5t** [comment]
@fb55 I vote to close this.

1. The reconnect shoudn't automatically happen during a close (ctubio/gdax-node@2ae06d1). It should only happen when the heartbeat dies or goes out of sync.
2. The dependency updates (ctubio/gdax-node@08be19b) are no longer relevant to the `master` branch.

**Comment by fb55** [comment]
Sgtm :)
