### ISSUE TITLE
Reliable way to get price updates?

### ISSUE THREAD

**Issue by IljaDaderko** [coinbase/gdax-node#85]
I'm trying to figure out a way to get current price reliably. At the moment my approach is to use websocket and listen for `match` events where I get price from.

But if volume is low i.e. `LTC-EUR` pair, these matches happen very very rarely, sometimes even don't happen at all within 5 minute period. I was trying to go through gdax docs and this was recommended way to get price updates, but doesn't look too accurate fro me at the moment, hence this question to see if there is a better way.

**Comment by fb55** [comment]
You currently need to maintain a level 3 book ([order book](https://github.com/coinbase/gdax-node#orderbook)) for this. This might be simplified in the future (see #82).
