### ISSUE TITLE
Promise example returns error

### ISSUE THREAD

**Issue by Mika83AC** [coinbase/gdax-node#92]
Hello everyone,

why is the call of the following most basic example (highlighted in the readme) giving an "must supply a callback" error?

```
async function yourFunction() {
  try {
    const products = await publicClient.getProducts();
  } catch(error) {
    /* ... */
  }
}

yourFunction(); 
```

Tried in Node 8.3.0 which supports async/await.

Regards,
Michael

**Comment by nikulis** [comment]
Hi Michael,

Can you let us know what version of `gdax` you have installed?

The latest version currently on npm - v0.4.2 - does not have a promise API. The promise support that is currently on master has not yet been included in a release.

**Comment by Mika83AC** [comment]
Ah, that's it! I use the npm version ... ;)

Thx!
