### ISSUE TITLE
Which charting library do you use in gdax.com?

### ISSUE THREAD

**Issue by bernatfortet** [coinbase/gdax-node#95]
I'm trying to create a crypto currencies alert system and I need to chart financial data.

Did you write your own library for charting the price of coins?

Thanks.

**Comment by fb55** [comment]
We built our own custom charting library on top of react and mobx and are thinking about open-sourcing it. For simple charts d3 will probably be okay.

**Comment by lxcid** [comment]
would love to learn about your custom charting library, even if its just an article describing the high level overview.

**Comment by parlays** [comment]
Yes please open source it.  That would be amazing!
