### ISSUE TITLE
b64secret - missunderstanding

### ISSUE THREAD

**Issue by BRadTone** [coinbase/gdax-node#96]
Due to authenticate user, can i get some help?
```
const key = 'your_api_key';
const b64secret = 'your_b64_secret';
const passphrase = 'your_passphrase';

const apiURI = 'https://api.gdax.com';
const sandboxURI = 'https://api-public.sandbox.gdax.com';

const authedClient = new Gdax.AuthenticatedClient(key, b64secret, passphrase, apiURI);
```
Now i used b64secret as a string a got when i generated apiKey on gdex.
After calling methods on autherClient i get:
`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object. using API nodejs`

How should i manage b64secret? What is it? Where can i get it?

**Comment by azamatsmith** [comment]
@BRadTone Your secret is displayed only one time when you create your api key in GDAX. If you lost it, just create a new one.

**Comment by fb55** [comment]
Thanks @azamatsmith!

**Comment by pranjul23** [comment]
Where do I see my b64secret ?
I can observe my APIkey and paraphrase ?

Thanks
